-- Order 自研业务基线：销售订单、订单明细、回款记录。
-- 本迁移只定义我们的销售订单流程；订货宝订单后续通过 Integration 映射到本业务模型。

CREATE TABLE order_sales_order (
    id                       BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                VARCHAR(64)    NOT NULL COMMENT '租户ID',
    order_no                 VARCHAR(50)    NOT NULL COMMENT '销售订单号，由Order编码规则生成',
    customer_id              BIGINT(20)     NOT NULL COMMENT 'CRM客户ID，跨服务引用',
    customer_code_snapshot   VARCHAR(50)    NULL COMMENT '下单时客户编号快照',
    customer_name_snapshot   VARCHAR(200)   NOT NULL COMMENT '下单时客户名称快照',
    contact_name_snapshot    VARCHAR(100)   NULL COMMENT '联系人快照',
    contact_phone_snapshot   VARCHAR(50)    NULL COMMENT '联系电话快照',
    region_code              VARCHAR(64)    NULL COMMENT '客户归属地区，关联 REGION 字典项',
    owner_sales_user_id      VARCHAR(64)    NULL COMMENT '归属销售用户ID',
    owner_sales_name         VARCHAR(100)   NULL COMMENT '归属销售名称快照',
    order_date               DATETIME(6)    NOT NULL COMMENT '销售日期',
    order_status_code        VARCHAR(64)    NOT NULL DEFAULT 'DRAFT' COMMENT '销售订单状态，关联 SALES_ORDER_STATUS 字典项',
    order_type_code          VARCHAR(64)    NULL COMMENT '订单类型，关联 ORDER_TYPE 字典项',
    payment_method_code      VARCHAR(64)    NULL COMMENT '付款方式，关联 PAYMENT_METHOD 字典项',
    payment_status_code      VARCHAR(64)    NOT NULL DEFAULT 'UNPAID' COMMENT '付款状态，关联 PAYMENT_STATUS 字典项',
    outbound_status_code     VARCHAR(64)    NOT NULL DEFAULT 'PENDING' COMMENT '出库状态，关联 OUTBOUND_STATUS 字典项',
    total_quantity           DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '订单总数量，由明细汇总',
    original_amount          DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '原价小计',
    discount_rate            DECIMAL(10,6)  NULL COMMENT '优惠比例',
    discount_amount          DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '优惠金额',
    payable_amount           DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '应收金额',
    paid_amount              DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '已收金额',
    unpaid_amount            DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '待收金额',
    remark                   VARCHAR(1000)  NULL COMMENT '备注',
    revision                 INT            NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
    created_by               VARCHAR(50)    NULL COMMENT '创建人',
    created_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by               VARCHAR(50)    NULL COMMENT '更新人',
    updated_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted                  INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_sales_order_no (tenant_id, order_no),
    KEY idx_order_sales_customer (tenant_id, customer_id),
    KEY idx_order_sales_region (tenant_id, region_code, order_date),
    KEY idx_order_sales_owner (tenant_id, owner_sales_user_id, order_date),
    KEY idx_order_sales_status (tenant_id, order_status_code, order_date),
    KEY idx_order_sales_payment (tenant_id, payment_status_code, order_date),
    KEY idx_order_sales_outbound (tenant_id, outbound_status_code, order_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单主表';

CREATE TABLE order_sales_order_line (
    id                          BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                   VARCHAR(64)    NOT NULL COMMENT '租户ID',
    order_id                    BIGINT(20)     NOT NULL COMMENT '销售订单ID',
    line_no                     INT            NOT NULL COMMENT '行号',
    product_id                  BIGINT(20)     NOT NULL COMMENT 'ERP商品ID，跨服务引用',
    product_variant_id          BIGINT(20)     NOT NULL COMMENT 'ERP商品规格ID，跨服务引用',
    product_code_snapshot       VARCHAR(128)   NULL COMMENT '商品编码快照',
    sku_code_snapshot           VARCHAR(128)   NULL COMMENT 'SKU编码快照',
    product_name_snapshot       VARCHAR(200)   NOT NULL COMMENT '商品名称快照',
    specification_snapshot      VARCHAR(500)   NULL COMMENT '规格快照',
    unit_code                   VARCHAR(64)    NOT NULL COMMENT '订货单位，关联 PRODUCT_UNIT 字典项',
    quantity                    DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '订货数量',
    unit_price                  DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '成交单价',
    discount_rate               DECIMAL(10,6)  NULL COMMENT '明细优惠比例',
    discount_amount             DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '明细优惠金额',
    line_amount                 DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '明细应收金额',
    remark                      VARCHAR(1000)  NULL COMMENT '备注',
    created_time                DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time                DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted                     INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    KEY idx_order_sales_line_no (tenant_id, order_id, line_no),
    CONSTRAINT fk_order_sales_line_order FOREIGN KEY (order_id) REFERENCES order_sales_order (id),
    KEY idx_order_sales_line_product (tenant_id, product_id, product_variant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单明细表';

CREATE TABLE order_payment_record (
    id                       BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                VARCHAR(64)    NOT NULL COMMENT '租户ID',
    payment_no               VARCHAR(50)    NOT NULL COMMENT '回款单号，由Order编码规则生成',
    order_id                 BIGINT(20)     NOT NULL COMMENT '销售订单ID',
    collector_user_id        VARCHAR(64)    NULL COMMENT '回款人用户ID',
    collector_name_snapshot  VARCHAR(100)   NULL COMMENT '回款人名称快照',
    payment_time             DATETIME(6)    NOT NULL COMMENT '回款时间',
    payment_method_code      VARCHAR(64)    NULL COMMENT '付款方式，关联 PAYMENT_METHOD 字典项',
    paid_amount              DECIMAL(24,6)  NOT NULL COMMENT '回款金额',
    voucher_keys_json        JSON           NULL COMMENT '付款凭证COS key数组',
    remark                   VARCHAR(1000)  NULL COMMENT '备注',
    revision                 INT            NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
    created_by               VARCHAR(50)    NULL COMMENT '创建人',
    created_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by               VARCHAR(50)    NULL COMMENT '更新人',
    updated_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted                  INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_payment_no (tenant_id, payment_no),
    CONSTRAINT fk_order_payment_order FOREIGN KEY (order_id) REFERENCES order_sales_order (id),
    KEY idx_order_payment_order (tenant_id, order_id, payment_time),
    KEY idx_order_payment_collector (tenant_id, collector_user_id, payment_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单回款记录表';
