-- 订货宝一期订单域只读单据：独立发货单、退货单、收款单、付款单及明细。
-- 所有表由Order Center独占写入；来源状态保留订货宝原值，不替代平台内部状态机。

CREATE TABLE order_dhb_shipment (
    id                   CHAR(36)      NOT NULL COMMENT '平台发货单投影ID，UUID',
    tenant_id            VARCHAR(64)   NOT NULL COMMENT '租户ID，来自可信签名上下文',
    source_system        VARCHAR(32)   NOT NULL DEFAULT 'DINGHUOBAO' COMMENT '来源系统，固定DINGHUOBAO',
    source_shipment_id   VARCHAR(100)  NULL COMMENT '订货宝发货单主键ships_id',
    shipment_no          VARCHAR(100)  NOT NULL COMMENT '订货宝发货单号ships_num，租户内幂等键',
    order_no             VARCHAR(100)  NULL COMMENT '关联订货宝订单号orders_num',
    source_status        VARCHAR(40)   NULL COMMENT '来源状态：shipped待发货、receivedin待收货、received已收货、cancelled已取消',
    source_status_name   VARCHAR(80)   NULL COMMENT '订货宝返回的状态中文名status_name',
    source_type_id       VARCHAR(40)   NULL COMMENT '出库类型ID：-2采购退货、10销售出库、11盘亏、17其他、18调拨、19联营',
    source_type_name     VARCHAR(80)   NULL COMMENT '订货宝出库类型名称type_name',
    customer_no          VARCHAR(100)  NULL COMMENT '客户编号client_num',
    customer_name        VARCHAR(200)  NULL COMMENT '客户名称快照client_name',
    customer_guid        VARCHAR(100)  NULL COMMENT '客户ERP外码client_guid',
    warehouse_no         VARCHAR(100)  NULL COMMENT '出库仓库编号stock_num',
    warehouse_name       VARCHAR(200)  NULL COMMENT '出库仓库名称stock_name',
    warehouse_guid       VARCHAR(100)  NULL COMMENT '出库仓库外码stock_guid',
    shipment_at          DATETIME(6)   NULL COMMENT '来源发货时间ships_date，统一存UTC',
    logistics_name       VARCHAR(200)  NULL COMMENT '物流公司名称logistics_name',
    tracking_no          VARCHAR(160)  NULL COMMENT '物流单号express_num',
    remark               VARCHAR(1000) NULL COMMENT '发货单备注remark',
    source_created_at    DATETIME(6)   NULL COMMENT '订货宝单据创建时间create_date，统一存UTC',
    source_updated_at    DATETIME(6)   NULL COMMENT '订货宝单据更新时间update_date，统一存UTC',
    raw_json             JSON          NOT NULL COMMENT '列表同步为getShipsList单条JSON；含详情时为list+detail组合JSON，不含Token',
    payload_hash         CHAR(64)      NOT NULL COMMENT 'raw_json的SHA-256十六进制摘要，用于幂等和变更检测',
    detail_available     TINYINT       NOT NULL DEFAULT 0 COMMENT '是否已保存getShipsContent明细：0否、1是',
    synced_at            DATETIME(6)   NOT NULL COMMENT '最近一次成功落库时间，UTC',
    created_at           DATETIME(6)   NOT NULL COMMENT '本地首次创建时间，UTC',
    updated_at           DATETIME(6)   NOT NULL COMMENT '本地最近更新时间，UTC',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_dhb_shipment_source (tenant_id, source_system, shipment_no),
    KEY idx_order_dhb_shipment_order (tenant_id, order_no),
    KEY idx_order_dhb_shipment_status (tenant_id, source_status, shipment_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='订货宝独立发货单只读本地投影';

CREATE TABLE order_dhb_shipment_line (
    id                   CHAR(36)      NOT NULL COMMENT '平台发货明细ID，UUID',
    shipment_id          CHAR(36)      NOT NULL COMMENT '所属order_dhb_shipment.id',
    source_line_id       VARCHAR(160)  NOT NULL COMMENT '来源明细ID；来源无ID时由Integration生成稳定键',
    source_product_guid  VARCHAR(100)  NULL COMMENT '商品ERP外码或订货宝商品ID',
    sku_no               VARCHAR(100)  NULL COMMENT '规格商品编码skuNo/options_goods_num',
    product_code         VARCHAR(100)  NULL COMMENT '商品编码coding',
    product_name         VARCHAR(240)  NULL COMMENT '商品名称name',
    quantity             DECIMAL(18,4) NULL COMMENT '本次发货数量，沿用来源小单位语义',
    unit_price           DECIMAL(18,4) NULL COMMENT 'orders_list_info.orders_price/order_units_price来源发货单价，最多4位小数',
    line_amount          DECIMAL(18,4) NULL COMMENT 'orders_list_info.actual_amount来源明细金额；来源无值时为空',
    unit_name            VARCHAR(80)   NULL COMMENT 'orders_list_info.order_units_name/base_units_name来源计量单位名称',
    warehouse_no         VARCHAR(100)  NULL COMMENT '主单stock_num出库仓库编号；明细未单独返回仓库时继承主单',
    remark               VARCHAR(1000) NULL COMMENT '发货明细备注',
    created_at           DATETIME(6)   NOT NULL COMMENT '本地创建时间，UTC',
    updated_at           DATETIME(6)   NOT NULL COMMENT '本地更新时间，UTC',
    PRIMARY KEY (id),
    CONSTRAINT fk_order_dhb_shipment_line FOREIGN KEY (shipment_id) REFERENCES order_dhb_shipment(id)
        ON DELETE CASCADE ON UPDATE RESTRICT,
    UNIQUE KEY uk_order_dhb_shipment_line (shipment_id, source_line_id),
    KEY idx_order_dhb_shipment_line_sku (sku_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='订货宝发货单商品明细只读本地投影';

CREATE TABLE order_dhb_return (
    id                   CHAR(36)      NOT NULL COMMENT '平台退货单投影ID，UUID',
    tenant_id            VARCHAR(64)   NOT NULL COMMENT '租户ID，来自可信签名上下文',
    source_system        VARCHAR(32)   NOT NULL DEFAULT 'DINGHUOBAO' COMMENT '来源系统，固定DINGHUOBAO',
    return_no            VARCHAR(100)  NOT NULL COMMENT '订货宝退货单号ReturnsSN，租户内幂等键',
    order_no             VARCHAR(100)  NULL COMMENT '关联订货宝订单号OrdersNum',
    source_status        VARCHAR(40)   NULL COMMENT '来源状态：return_audit待审核、shipp_cust待客户发货、shipped待收货、refunded待退款、finished已完成、cancelled已取消',
    staff_name           VARCHAR(160)  NULL COMMENT '退货单经办人StaffName',
    return_amount        DECIMAL(18,4) NULL COMMENT '退单金额ReturnsTotal',
    settlement_amount    DECIMAL(18,4) NULL COMMENT '退单结算金额ReturnsDiscountTotal',
    returned_at          DATETIME(6)   NULL COMMENT '退货单日期ReturnsDate，统一存UTC',
    source_updated_at    DATETIME(6)   NULL COMMENT '退货单更新时间ReturnsUpdateDate，统一存UTC',
    reason               VARCHAR(1000) NULL COMMENT '退货原因ReturnsReason',
    customer_no          VARCHAR(100)  NULL COMMENT '客户编号ClientNum',
    customer_guid        VARCHAR(100)  NULL COMMENT '客户ERP外码ClientGUID',
    consignee            VARCHAR(160)  NULL COMMENT '退单收货人ReturnsConsignee',
    phone                VARCHAR(64)   NULL COMMENT '退单联系电话ReturnsPhone，前端按权限脱敏',
    address              VARCHAR(500)  NULL COMMENT '退货地址ReturnsAddress，前端按权限脱敏',
    logistics_company    VARCHAR(200)  NULL COMMENT '退货物流公司ReturnsSendCompany',
    logistics_no         VARCHAR(160)  NULL COMMENT '退货物流单号ReturnsSendNo',
    return_type          VARCHAR(16)   NULL COMMENT '退货类型：0未确认、1退货退款、2仅退款',
    delivery_mode        VARCHAR(100)  NULL COMMENT '退货配送方式ReturnsSendMode',
    raw_json             JSON          NOT NULL COMMENT '列表同步为getReturnsList单条JSON；含详情时为list+detail组合JSON，不含Token',
    payload_hash         CHAR(64)      NOT NULL COMMENT 'raw_json的SHA-256十六进制摘要，用于幂等和变更检测',
    detail_available     TINYINT       NOT NULL DEFAULT 0 COMMENT '是否已保存getReturnsContent明细：0否、1是',
    synced_at            DATETIME(6)   NOT NULL COMMENT '最近一次成功落库时间，UTC',
    created_at           DATETIME(6)   NOT NULL COMMENT '本地首次创建时间，UTC',
    updated_at           DATETIME(6)   NOT NULL COMMENT '本地最近更新时间，UTC',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_dhb_return_source (tenant_id, source_system, return_no),
    KEY idx_order_dhb_return_order (tenant_id, order_no),
    KEY idx_order_dhb_return_status (tenant_id, source_status, returned_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='订货宝退货单只读本地投影';

CREATE TABLE order_dhb_return_line (
    id                   CHAR(36)      NOT NULL COMMENT '平台退货明细ID，UUID',
    return_id            CHAR(36)      NOT NULL COMMENT '所属order_dhb_return.id',
    source_line_id       VARCHAR(160)  NOT NULL COMMENT '来源明细ID；来源无ID时由Integration生成稳定键',
    source_product_guid  VARCHAR(100)  NULL COMMENT '商品ERP外码Guid/TrueGuid',
    sku_no               VARCHAR(100)  NULL COMMENT '规格商品编码OptionsGoodsNum',
    product_code         VARCHAR(100)  NULL COMMENT '商品编码Coding',
    product_name         VARCHAR(240)  NULL COMMENT '商品名称Name',
    quantity             DECIMAL(18,4) NULL COMMENT '申请退货数量ReturnsNumber',
    confirmed_quantity   DECIMAL(18,4) NULL COMMENT '确认退货数量ReturnsConfirmNumber',
    unit_price           DECIMAL(18,4) NULL COMMENT '申请退货价格ReturnsPrice',
    confirmed_price      DECIMAL(18,4) NULL COMMENT '确认退货价格ReturnsConfirmPrice',
    unit_name            VARCHAR(80)   NULL COMMENT '退货单位名称ReturnsUnitsName',
    warehouse_no         VARCHAR(100)  NULL COMMENT 'body.Stock.StockGuid或StockId退货仓库外码/编号',
    warehouse_name       VARCHAR(200)  NULL COMMENT 'body.Stock.StockName退货仓库名称',
    remark               VARCHAR(1000) NULL COMMENT '退货明细备注ReturnsRemark',
    created_at           DATETIME(6)   NOT NULL COMMENT '本地创建时间，UTC',
    updated_at           DATETIME(6)   NOT NULL COMMENT '本地更新时间，UTC',
    PRIMARY KEY (id),
    CONSTRAINT fk_order_dhb_return_line FOREIGN KEY (return_id) REFERENCES order_dhb_return(id)
        ON DELETE CASCADE ON UPDATE RESTRICT,
    UNIQUE KEY uk_order_dhb_return_line (return_id, source_line_id),
    KEY idx_order_dhb_return_line_sku (sku_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='订货宝退货单商品明细只读本地投影';

CREATE TABLE order_dhb_financial_document (
    id                   CHAR(36)      NOT NULL COMMENT '平台收付款投影ID，UUID',
    tenant_id            VARCHAR(64)   NOT NULL COMMENT '租户ID，来自可信签名上下文',
    source_system        VARCHAR(32)   NOT NULL DEFAULT 'DINGHUOBAO' COMMENT '来源系统，固定DINGHUOBAO',
    document_type        VARCHAR(16)   NOT NULL COMMENT '单据类型：RECEIPT收款单、PAYMENT付款单',
    document_no          VARCHAR(100)  NOT NULL COMMENT '收款单ReceiptsNum或付款单PaymentNum，租户内幂等键',
    related_document_no  VARCHAR(100)  NULL COMMENT '付款关联收款单ReceiptsNum等来源关联单号',
    order_no             VARCHAR(100)  NULL COMMENT '关联订货宝订单号OrdersNum',
    customer_no          VARCHAR(100)  NULL COMMENT '客户编号ClientNum',
    customer_guid        VARCHAR(100)  NULL COMMENT '客户ERP外码ClientGuid',
    business_type        VARCHAR(40)   NULL COMMENT 'IncexpId：1普通充值、19预付款充值、13订单收款、8期初充值、2退货退款、10退款失败回冲、9退款红冲；其他值原样保存',
    payment_method       VARCHAR(100)  NULL COMMENT '来源支付方式兼容字段TypeId；当前官方收付款列表可能不返回，未返回时为空',
    amount               DECIMAL(18,4) NULL COMMENT '收款或付款金额Amount，最多4位小数',
    source_status        VARCHAR(40)   NULL COMMENT '来源状态：pend_receipt待确认、pend_receipted已确认、canceled已取消；来源未返回时为空',
    transaction_at       DATETIME(6)   NULL COMMENT '来源转账日期ReceiptsDate，统一存UTC',
    source_created_at    DATETIME(6)   NULL COMMENT '来源录入时间CreateDate，统一存UTC',
    source_updated_at    DATETIME(6)   NULL COMMENT '来源修改时间UpdateDate，统一存UTC',
    serial_number        VARCHAR(160)  NULL COMMENT '来源收付款流水号SerialNumber',
    account_name         VARCHAR(200)  NULL COMMENT '来源开户名称AccountName',
    bank_name            VARCHAR(200)  NULL COMMENT '来源开户行BankName',
    account_number       VARCHAR(200)  NULL COMMENT '来源银行账号AccountNumber，前端按权限脱敏',
    remark               VARCHAR(1000) NULL COMMENT '来源备注Remark',
    raw_json             JSON          NOT NULL COMMENT 'getReceiptsList或getPaymentList的单据原始JSON，不含Token',
    payload_hash         CHAR(64)      NOT NULL COMMENT 'raw_json的SHA-256十六进制摘要，用于幂等和变更检测',
    synced_at            DATETIME(6)   NOT NULL COMMENT '最近一次成功落库时间，UTC',
    created_at           DATETIME(6)   NOT NULL COMMENT '本地首次创建时间，UTC',
    updated_at           DATETIME(6)   NOT NULL COMMENT '本地最近更新时间，UTC',
    PRIMARY KEY (id),
    CONSTRAINT ck_order_dhb_financial_type CHECK (document_type IN ('RECEIPT', 'PAYMENT')),
    UNIQUE KEY uk_order_dhb_financial_source (tenant_id, source_system, document_type, document_no),
    KEY idx_order_dhb_financial_order (tenant_id, order_no),
    KEY idx_order_dhb_financial_status (tenant_id, document_type, source_status, transaction_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='订货宝收款单和付款单只读本地投影';
