-- Analytics BI：供应链经营看板事实/维度表与刷新任务状态。
--
-- 看板正式请求只聚合本 schema 下 BI 表；跨业务源库 SQL 仅用于 BI 服务刷新任务。

CREATE TABLE bi_customer_dim (
    id                   BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id            VARCHAR(64)   NOT NULL COMMENT '租户ID',
    customer_id          BIGINT(20)    NOT NULL COMMENT 'CRM客户ID',
    customer_code        VARCHAR(50)   NULL COMMENT '客户编号快照',
    customer_name        VARCHAR(200)  NULL COMMENT '客户/门店名称快照',
    region_code          VARCHAR(64)   NULL COMMENT '城市/区域编码快照',
    owner_staff_code     VARCHAR(50)   NULL COMMENT '归属销售员工编码快照',
    owner_staff_name     VARCHAR(100)  NULL COMMENT '归属销售姓名快照',
    customer_type_code   VARCHAR(64)   NULL COMMENT '客户类型编码快照',
    status_code          VARCHAR(64)   NULL COMMENT '客户状态编码快照',
    source_updated_time  DATETIME(6)   NULL COMMENT '源表更新时间水位',
    synced_time          DATETIME(6)   NOT NULL COMMENT '同步到BI时间',
    deleted              INT           NOT NULL DEFAULT 0 COMMENT '源逻辑删除标识',
    created_time         DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time         DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_bi_customer_dim_source (tenant_id, customer_id),
    KEY idx_bi_customer_dim_region (tenant_id, region_code, deleted),
    KEY idx_bi_customer_dim_owner (tenant_id, owner_staff_code, deleted),
    KEY idx_bi_customer_dim_type (tenant_id, customer_type_code, deleted),
    KEY idx_bi_customer_dim_updated (tenant_id, source_updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='BI客户/门店维度';

CREATE TABLE bi_sales_order_fact (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    order_id              BIGINT(20)     NOT NULL COMMENT '销售订单ID',
    order_no              VARCHAR(50)    NULL COMMENT '销售订单号快照',
    source_system_code    VARCHAR(32)    NOT NULL DEFAULT 'MANUAL' COMMENT '来源系统编码',
    source_order_no       VARCHAR(80)    NULL COMMENT '来源平台订单号',
    customer_id           BIGINT(20)     NULL COMMENT 'CRM客户ID',
    customer_code         VARCHAR(50)    NULL COMMENT '客户编号快照',
    customer_name         VARCHAR(200)   NULL COMMENT '客户名称快照',
    customer_type_code    VARCHAR(64)    NULL COMMENT '客户类型编码快照',
    customer_status_code  VARCHAR(64)    NULL COMMENT '客户状态编码快照',
    region_code           VARCHAR(64)    NULL COMMENT '城市/区域编码快照',
    owner_staff_code      VARCHAR(50)    NULL COMMENT '归属销售员工编码快照',
    owner_staff_name      VARCHAR(100)   NULL COMMENT '归属销售姓名快照',
    order_date            DATETIME(6)    NOT NULL COMMENT '销售日期',
    payment_time          DATETIME(6)    NULL COMMENT '付款时间快照',
    shipment_time         DATETIME(6)    NULL COMMENT '发货时间快照',
    order_status_code     VARCHAR(64)    NULL COMMENT '订单状态编码',
    payment_status_code   VARCHAR(64)    NULL COMMENT '收款状态编码',
    outbound_status_code  VARCHAR(64)    NULL COMMENT '出库状态编码',
    order_type_code       VARCHAR(64)    NULL COMMENT '订单类型编码',
    total_quantity        DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '订单数量',
    payable_amount        DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '应收金额',
    paid_amount           DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '已收金额',
    unpaid_amount         DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '待收金额',
    source_updated_time   DATETIME(6)    NULL COMMENT '源数据更新时间水位',
    synced_time           DATETIME(6)    NOT NULL COMMENT '同步到BI时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '源逻辑删除标识',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_bi_sales_order_fact_source (tenant_id, order_id),
    KEY idx_bi_sales_order_fact_date (tenant_id, order_date, deleted),
    KEY idx_bi_sales_order_fact_region (tenant_id, region_code, order_date),
    KEY idx_bi_sales_order_fact_owner (tenant_id, owner_staff_code, order_date),
    KEY idx_bi_sales_order_fact_customer (tenant_id, customer_id, order_date),
    KEY idx_bi_sales_order_fact_source_sys (tenant_id, source_system_code, order_date),
    KEY idx_bi_sales_order_fact_updated (tenant_id, source_updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='BI销售订单事实';

CREATE TABLE bi_sales_payment_fact (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    payment_id            BIGINT(20)     NOT NULL COMMENT '销售回款记录ID',
    payment_no            VARCHAR(50)    NULL COMMENT '回款单号快照',
    order_id              BIGINT(20)     NULL COMMENT '销售订单ID',
    order_no              VARCHAR(50)    NULL COMMENT '销售订单号快照',
    source_system_code    VARCHAR(32)    NOT NULL DEFAULT 'MANUAL' COMMENT '来源系统编码',
    customer_id           BIGINT(20)     NULL COMMENT 'CRM客户ID',
    customer_code         VARCHAR(50)    NULL COMMENT '客户编号快照',
    customer_name         VARCHAR(200)   NULL COMMENT '客户名称快照',
    customer_type_code    VARCHAR(64)    NULL COMMENT '客户类型编码快照',
    region_code           VARCHAR(64)    NULL COMMENT '城市/区域编码快照',
    owner_staff_code      VARCHAR(50)    NULL COMMENT '订单归属销售员工编码快照',
    owner_staff_name      VARCHAR(100)   NULL COMMENT '订单归属销售姓名快照',
    collector_staff_code  VARCHAR(50)    NULL COMMENT '回款人员工编码快照',
    collector_staff_name  VARCHAR(100)   NULL COMMENT '回款人姓名快照',
    payment_time          DATETIME(6)    NOT NULL COMMENT '回款时间',
    payment_method_code   VARCHAR(64)    NULL COMMENT '付款方式编码',
    paid_amount           DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '回款金额',
    source_updated_time   DATETIME(6)    NULL COMMENT '源数据更新时间水位',
    synced_time           DATETIME(6)    NOT NULL COMMENT '同步到BI时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '源逻辑删除标识',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_bi_sales_payment_fact_source (tenant_id, payment_id),
    KEY idx_bi_sales_payment_fact_time (tenant_id, payment_time, deleted),
    KEY idx_bi_sales_payment_fact_customer (tenant_id, customer_id, payment_time),
    KEY idx_bi_sales_payment_fact_collector (tenant_id, collector_staff_code, payment_time),
    KEY idx_bi_sales_payment_fact_owner (tenant_id, owner_staff_code, payment_time),
    KEY idx_bi_sales_payment_fact_source_sys (tenant_id, source_system_code, payment_time),
    KEY idx_bi_sales_payment_fact_updated (tenant_id, source_updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='BI销售回款事实';

CREATE TABLE bi_inventory_balance_current (
    id                       BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                VARCHAR(64)    NOT NULL COMMENT '租户ID',
    warehouse_id             BIGINT(20)     NOT NULL COMMENT 'ERP仓库ID',
    warehouse_code           VARCHAR(50)    NULL COMMENT '仓库编码快照',
    warehouse_name           VARCHAR(120)   NULL COMMENT '仓库名称快照',
    region_code              VARCHAR(64)    NULL COMMENT '仓库城市/区域编码快照',
    product_id               BIGINT(20)     NOT NULL COMMENT 'ERP商品ID',
    product_code             VARCHAR(50)    NULL COMMENT '商品编码快照',
    product_name             VARCHAR(200)   NULL COMMENT '商品名称快照',
    product_category_id      BIGINT(20)     NULL COMMENT '商品分类ID快照',
    product_variant_id       BIGINT(20)     NOT NULL COMMENT 'ERP商品规格ID',
    variant_code             VARCHAR(50)    NULL COMMENT '规格编码快照',
    specification_snapshot   VARCHAR(500)   NULL COMMENT '规格描述快照',
    available_quantity       DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '可用库存',
    locked_quantity          DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '锁定库存',
    in_transit_quantity      DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '在途库存',
    source_updated_time      DATETIME(6)    NULL COMMENT '源数据更新时间水位',
    synced_time              DATETIME(6)    NOT NULL COMMENT '同步到BI时间',
    deleted                  INT            NOT NULL DEFAULT 0 COMMENT '源维度不可用或被本次快照淘汰',
    created_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_bi_inventory_balance_current_source (tenant_id, warehouse_id, product_id, product_variant_id),
    KEY idx_bi_inventory_balance_current_region (tenant_id, region_code, deleted),
    KEY idx_bi_inventory_balance_current_product (tenant_id, product_id, product_variant_id),
    KEY idx_bi_inventory_balance_current_category (tenant_id, product_category_id, deleted),
    KEY idx_bi_inventory_balance_current_risk (tenant_id, available_quantity, locked_quantity),
    KEY idx_bi_inventory_balance_current_updated (tenant_id, source_updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='BI当前库存余额快照';

CREATE TABLE bi_etl_checkpoint (
    id                    BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)   NOT NULL COMMENT '租户ID',
    source_code           VARCHAR(64)   NOT NULL COMMENT '来源编码或任务锁编码',
    source_name           VARCHAR(120)  NULL COMMENT '来源名称',
    last_watermark_time   DATETIME(6)   NULL COMMENT '上次成功处理水位',
    last_success_time     DATETIME(6)   NULL COMMENT '上次成功时间',
    last_run_id           BIGINT(20)    NULL COMMENT '最近成功运行ID',
    status_code           VARCHAR(32)   NOT NULL DEFAULT 'IDLE' COMMENT '状态：IDLE/RUNNING/SUCCESS/FAILED',
    locked_until          DATETIME(6)   NULL COMMENT '运行锁过期时间',
    failure_reason        VARCHAR(1000) NULL COMMENT '最近失败原因',
    created_time          DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_bi_etl_checkpoint_source (tenant_id, source_code),
    KEY idx_bi_etl_checkpoint_status (tenant_id, status_code, locked_until),
    KEY idx_bi_etl_checkpoint_watermark (tenant_id, source_code, last_watermark_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='BI ETL水位与运行锁';

CREATE TABLE bi_etl_run (
    id                    BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)   NOT NULL COMMENT '租户ID',
    job_code              VARCHAR(64)   NOT NULL COMMENT '任务编码',
    status_code           VARCHAR(32)   NOT NULL COMMENT '状态：RUNNING/SUCCESS/FAILED/SKIPPED',
    started_time          DATETIME(6)   NOT NULL COMMENT '开始时间',
    completed_time        DATETIME(6)   NULL COMMENT '完成时间',
    watermark_time        DATETIME(6)   NULL COMMENT '本次处理到的最大源更新时间',
    pulled_count          BIGINT(20)    NOT NULL DEFAULT 0 COMMENT '源读取数量',
    upserted_count        BIGINT(20)    NOT NULL DEFAULT 0 COMMENT 'BI写入影响数量',
    skipped_count         BIGINT(20)    NOT NULL DEFAULT 0 COMMENT '跳过数量',
    failure_reason        VARCHAR(1000) NULL COMMENT '失败原因',
    created_time          DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_bi_etl_run_tenant_job (tenant_id, job_code, started_time),
    KEY idx_bi_etl_run_status (tenant_id, job_code, status_code, started_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='BI ETL运行记录';
