server:
  port: 26883

spring:
  application:
    name: rigour-merchant-crm-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.rigour: INFO
