spring:
  datasource:
    url: ${RIGOUR_COLLABORATION_DB_URL:jdbc:mysql://127.0.0.1:3306/rigour_collaboration?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${RIGOUR_COLLABORATION_DB_USERNAME:rigour_collaboration_app}
    password: ${RIGOUR_COLLABORATION_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
