-- ERP 自研采购退货业务表。
-- 采购退货是采购域业务单据，不再落到旧订货宝投影表，也不直接混入通用出库单。
-- 后续需要扣减库存时，由采购退货单生成或关联出库动作。

CREATE TABLE erp_purchase_return_order (
    id                            BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                     VARCHAR(64)    NOT NULL COMMENT '租户ID',
    purchase_return_no            VARCHAR(50)    NOT NULL COMMENT '采购退货单号，由ERP编码规则生成',
    supplier_id                   BIGINT(20)     NOT NULL COMMENT '供应商ID',
    warehouse_id                  BIGINT(20)     NOT NULL COMMENT '退货出库仓库ID',
    operator_staff_code           VARCHAR(50)    NULL COMMENT '经办员工编码，关联IAM员工中心员工编码',
    operator_staff_name_snapshot  VARCHAR(100)   NULL COMMENT '经办员工名称快照',
    status_code                   VARCHAR(64)    NOT NULL DEFAULT 'DRAFT' COMMENT '采购退货状态，关联 PURCHASE_RETURN_STATUS 字典项',
    total_quantity                DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '退货总数量，由明细汇总或来源换算',
    total_amount                  DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '退货总金额',
    discount_amount               DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '优惠/折让金额',
    return_time                   DATETIME(6)    NULL COMMENT '退货发出时间',
    contact_name                  VARCHAR(100)   NULL COMMENT '联系人',
    contact_phone                 VARCHAR(50)    NULL COMMENT '联系电话',
    contact_address               VARCHAR(1000)  NULL COMMENT '联系地址',
    reason                        VARCHAR(1000)  NULL COMMENT '退货原因',
    remark                        VARCHAR(1000)  NULL COMMENT '备注',
    revision                      INT            NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by                    VARCHAR(50)    NULL COMMENT '创建人',
    created_time                  DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by                    VARCHAR(50)    NULL COMMENT '更新人',
    updated_time                  DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted                       INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_purchase_return_order_no (tenant_id, purchase_return_no),
    CONSTRAINT fk_erp_purchase_return_order_supplier FOREIGN KEY (supplier_id) REFERENCES erp_supplier_profile (id),
    CONSTRAINT fk_erp_purchase_return_order_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_inventory_warehouse (id),
    KEY idx_erp_purchase_return_order_supplier (tenant_id, supplier_id, created_time),
    KEY idx_erp_purchase_return_order_warehouse (tenant_id, warehouse_id, return_time),
    KEY idx_erp_purchase_return_order_staff (tenant_id, operator_staff_code, created_time),
    KEY idx_erp_purchase_return_order_status (tenant_id, status_code, created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP采购退货单';

CREATE TABLE erp_purchase_return_order_line (
    id                         BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                  VARCHAR(64)    NOT NULL COMMENT '租户ID',
    purchase_return_order_id   BIGINT(20)     NOT NULL COMMENT '采购退货单ID',
    line_no                    INT            NOT NULL COMMENT '行号',
    procurement_order_id       BIGINT(20)     NULL COMMENT '关联采购订单ID；可由来源采购单号映射到ERP自研采购单',
    procurement_no_snapshot    VARCHAR(50)    NULL COMMENT '关联采购订单号快照',
    product_id                 BIGINT(20)     NOT NULL COMMENT '商品ID',
    product_variant_id         BIGINT(20)     NOT NULL COMMENT '商品规格ID',
    product_code_snapshot      VARCHAR(50)    NULL COMMENT '商品编码快照',
    variant_code_snapshot      VARCHAR(50)    NULL COMMENT '商品规格编码快照',
    product_name_snapshot      VARCHAR(200)   NOT NULL COMMENT '商品名称快照',
    unit_code                  VARCHAR(64)    NOT NULL COMMENT '退货单位，关联 PRODUCT_UNIT 字典项',
    requested_quantity         DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '申请退货数量',
    returned_quantity          DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '确认退货数量',
    unit_price                 DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '退货单价',
    confirmed_unit_price       DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '确认退货单价',
    line_amount                DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '明细金额',
    cost_price                 DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '成本价快照',
    remark                     VARCHAR(1000)  NULL COMMENT '备注',
    created_time               DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time               DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted                    INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    KEY idx_erp_purchase_return_line_no (tenant_id, purchase_return_order_id, line_no, deleted),
    KEY idx_erp_purchase_return_line_procurement (tenant_id, procurement_order_id),
    KEY idx_erp_purchase_return_line_product (tenant_id, product_id, product_variant_id),
    CONSTRAINT fk_erp_purchase_return_line_order FOREIGN KEY (purchase_return_order_id) REFERENCES erp_purchase_return_order (id),
    CONSTRAINT fk_erp_purchase_return_line_procurement FOREIGN KEY (procurement_order_id) REFERENCES erp_procurement_order (id),
    CONSTRAINT fk_erp_purchase_return_line_product FOREIGN KEY (product_id) REFERENCES erp_product (id),
    CONSTRAINT fk_erp_purchase_return_line_variant FOREIGN KEY (product_variant_id) REFERENCES erp_product_variant (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP采购退货单明细';
