-- ERP Core Schema V3：供应商、采购、采购退货、入库、仓库与库存规范模型。
-- Integration 独占订货宝协议与 Raw Landing；ERP 仅保存可查询的规范字段、来源快照和幂等键。

CREATE TABLE erp_supplier (
    id                       CHAR(36)       NOT NULL,
    tenant_id                VARCHAR(64)    NOT NULL,
    supplier_code            VARCHAR(128)   NOT NULL,
    name                     VARCHAR(200)   NOT NULL,
    source_supplier_id       VARCHAR(128)   NULL,
    source_supplier_guid     VARCHAR(128)   NULL,
    area_name                VARCHAR(200)   NULL,
    address_masked           VARCHAR(500)   NULL,
    contact_name             VARCHAR(120)   NULL,
    mobile_masked            VARCHAR(80)    NULL,
    phone_masked             VARCHAR(80)    NULL,
    email_masked             VARCHAR(200)   NULL,
    account_name             VARCHAR(200)   NULL,
    bank_name                VARCHAR(200)   NULL,
    bank_account_last4       VARCHAR(16)    NULL,
    invoice_title            VARCHAR(240)   NULL,
    taxpayer_number_masked   VARCHAR(80)    NULL,
    remark                   VARCHAR(1000)  NULL,
    internal_status          VARCHAR(24)    NOT NULL DEFAULT 'ACTIVE',
    ownership_state          VARCHAR(32)    NOT NULL DEFAULT 'EXTERNAL_PRIMARY',
    record_origin            VARCHAR(16)    NOT NULL DEFAULT 'IMPORTED',
    source_updated_at        DATETIME(6)    NULL,
    source_synced_at         DATETIME(6)    NOT NULL,
    attributes_json          JSON           NULL,
    version                  BIGINT         NOT NULL DEFAULT 0,
    created_by               CHAR(36)       NULL,
    updated_by               CHAR(36)       NULL,
    created_at               DATETIME(6)    NOT NULL,
    updated_at               DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_supplier_code UNIQUE (tenant_id, supplier_code),
    CONSTRAINT uk_erp_supplier_source UNIQUE (tenant_id, source_supplier_id),
    KEY idx_erp_supplier_name (tenant_id, name),
    KEY idx_erp_supplier_status (tenant_id, internal_status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP供应商档案';

CREATE TABLE erp_warehouse (
    id                       CHAR(36)       NOT NULL,
    tenant_id                VARCHAR(64)    NOT NULL,
    warehouse_code           VARCHAR(128)   NOT NULL,
    name                     VARCHAR(200)   NOT NULL,
    source_warehouse_id      VARCHAR(128)   NULL,
    source_warehouse_guid    VARCHAR(128)   NULL,
    source_status            VARCHAR(24)    NULL,
    source_default_flag      TINYINT(1)     NOT NULL DEFAULT 0,
    acreage                  DECIMAL(20,6)  NULL,
    phone_masked             VARCHAR(80)    NULL,
    address                  VARCHAR(500)   NULL,
    collaborator_source_id   VARCHAR(128)   NULL,
    remark                   VARCHAR(1000)  NULL,
    internal_status          VARCHAR(24)    NOT NULL DEFAULT 'ACTIVE',
    ownership_state          VARCHAR(32)    NOT NULL DEFAULT 'EXTERNAL_PRIMARY',
    record_origin            VARCHAR(16)    NOT NULL DEFAULT 'IMPORTED',
    source_synced_at         DATETIME(6)    NOT NULL,
    attributes_json          JSON           NULL,
    version                  BIGINT         NOT NULL DEFAULT 0,
    created_by               CHAR(36)       NULL,
    updated_by               CHAR(36)       NULL,
    created_at               DATETIME(6)    NOT NULL,
    updated_at               DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_warehouse_code UNIQUE (tenant_id, warehouse_code),
    CONSTRAINT uk_erp_warehouse_source UNIQUE (tenant_id, source_warehouse_id),
    KEY idx_erp_warehouse_name (tenant_id, name),
    KEY idx_erp_warehouse_status (tenant_id, internal_status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP仓库档案';

CREATE TABLE erp_purchase_order (
    id                       CHAR(36)       NOT NULL,
    tenant_id                VARCHAR(64)    NOT NULL,
    purchase_order_no        VARCHAR(128)   NOT NULL,
    source_purchase_id       VARCHAR(128)   NULL,
    supplier_id              CHAR(36)       NULL,
    warehouse_id             CHAR(36)       NULL,
    supplier_code_snapshot   VARCHAR(128)   NULL,
    supplier_name_snapshot   VARCHAR(200)   NULL,
    warehouse_code_snapshot  VARCHAR(128)   NULL,
    warehouse_name_snapshot  VARCHAR(200)   NULL,
    staff_source_id          VARCHAR(128)   NULL,
    staff_name               VARCHAR(120)   NULL,
    source_status            VARCHAR(32)    NULL,
    source_status_name       VARCHAR(80)    NULL,
    source_payment_status    VARCHAR(32)    NULL,
    source_payment_name      VARCHAR(80)    NULL,
    internal_status          VARCHAR(24)    NOT NULL DEFAULT 'DRAFT',
    delivery_at              DATETIME(6)    NULL,
    source_created_at        DATETIME(6)    NULL,
    source_updated_at        DATETIME(6)    NULL,
    total_amount             DECIMAL(20,6)  NOT NULL DEFAULT 0,
    paid_amount              DECIMAL(20,6)  NOT NULL DEFAULT 0,
    goods_count              DECIMAL(20,6)  NOT NULL DEFAULT 0,
    source_downloaded        TINYINT(1)     NOT NULL DEFAULT 0,
    remark                   VARCHAR(1000)  NULL,
    internal_communication   VARCHAR(2000)  NULL,
    ownership_state          VARCHAR(32)    NOT NULL DEFAULT 'EXTERNAL_PRIMARY',
    record_origin            VARCHAR(16)    NOT NULL DEFAULT 'IMPORTED',
    source_synced_at         DATETIME(6)    NOT NULL,
    attributes_json          JSON           NULL,
    version                  BIGINT         NOT NULL DEFAULT 0,
    created_by               CHAR(36)       NULL,
    updated_by               CHAR(36)       NULL,
    created_at               DATETIME(6)    NOT NULL,
    updated_at               DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_purchase_order_no UNIQUE (tenant_id, purchase_order_no),
    CONSTRAINT uk_erp_purchase_order_source UNIQUE (tenant_id, source_purchase_id),
    CONSTRAINT fk_erp_purchase_order_supplier FOREIGN KEY (supplier_id) REFERENCES erp_supplier (id),
    CONSTRAINT fk_erp_purchase_order_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_warehouse (id),
    KEY idx_erp_purchase_order_supplier (tenant_id, supplier_id, source_created_at),
    KEY idx_erp_purchase_order_status (tenant_id, internal_status, source_updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP采购单主表';

CREATE TABLE erp_purchase_order_line (
    id                         CHAR(36)       NOT NULL,
    tenant_id                  VARCHAR(64)    NOT NULL,
    purchase_order_id          CHAR(36)       NOT NULL,
    source_line_id             VARCHAR(128)   NOT NULL,
    spu_id                     CHAR(36)       NULL,
    sku_id                     CHAR(36)       NULL,
    source_goods_id            VARCHAR(128)   NULL,
    source_goods_guid          VARCHAR(128)   NULL,
    source_goods_code          VARCHAR(128)   NULL,
    source_goods_name          VARCHAR(240)   NULL,
    source_options_id          VARCHAR(128)   NULL,
    source_options_goods_code  VARCHAR(128)   NULL,
    options_summary            VARCHAR(500)   NULL,
    base_quantity              DECIMAL(20,6)  NOT NULL DEFAULT 0,
    unit_price                 DECIMAL(20,6)  NOT NULL DEFAULT 0,
    purchase_unit_code         VARCHAR(40)    NULL,
    purchase_unit_name         VARCHAR(80)    NULL,
    purchase_unit_quantity     DECIMAL(20,6)  NOT NULL DEFAULT 0,
    warehoused_quantity        DECIMAL(20,6)  NOT NULL DEFAULT 0,
    returned_quantity          DECIMAL(20,6)  NOT NULL DEFAULT 0,
    remark                     VARCHAR(1000)  NULL,
    attributes_json            JSON           NULL,
    created_at                 DATETIME(6)    NOT NULL,
    updated_at                 DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_purchase_order_line UNIQUE (tenant_id, purchase_order_id, source_line_id),
    CONSTRAINT fk_erp_purchase_order_line_order FOREIGN KEY (purchase_order_id) REFERENCES erp_purchase_order (id),
    CONSTRAINT fk_erp_purchase_order_line_spu FOREIGN KEY (spu_id) REFERENCES erp_product_spu (id),
    CONSTRAINT fk_erp_purchase_order_line_sku FOREIGN KEY (sku_id) REFERENCES erp_product_sku (id),
    KEY idx_erp_purchase_order_line_goods (tenant_id, source_goods_code, source_options_goods_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP采购单明细';

CREATE TABLE erp_purchase_return (
    id                       CHAR(36)       NOT NULL,
    tenant_id                VARCHAR(64)    NOT NULL,
    purchase_return_no       VARCHAR(128)   NOT NULL,
    source_return_id         VARCHAR(128)   NULL,
    supplier_id              CHAR(36)       NULL,
    warehouse_id             CHAR(36)       NULL,
    supplier_code_snapshot   VARCHAR(128)   NULL,
    supplier_name_snapshot   VARCHAR(200)   NULL,
    warehouse_code_snapshot  VARCHAR(128)   NULL,
    warehouse_name_snapshot  VARCHAR(200)   NULL,
    staff_source_id          VARCHAR(128)   NULL,
    staff_name               VARCHAR(120)   NULL,
    source_status            VARCHAR(32)    NULL,
    source_status_name       VARCHAR(80)    NULL,
    internal_status          VARCHAR(24)    NOT NULL DEFAULT 'DRAFT',
    return_amount            DECIMAL(20,6)  NOT NULL DEFAULT 0,
    discount_amount          DECIMAL(20,6)  NOT NULL DEFAULT 0,
    return_reason            VARCHAR(1000)  NULL,
    source_created_at        DATETIME(6)    NULL,
    return_send_at           DATETIME(6)    NULL,
    internal_communication   VARCHAR(2000)  NULL,
    remark                   VARCHAR(1000)  NULL,
    detail_count             INT            NOT NULL DEFAULT 0,
    contact_name             VARCHAR(120)   NULL,
    contact_phone_masked     VARCHAR(80)    NULL,
    contact_address_masked   VARCHAR(500)   NULL,
    city_ids_json            JSON           NULL,
    city_names_json          JSON           NULL,
    source_device            VARCHAR(80)    NULL,
    parent_return_source_id  VARCHAR(128)   NULL,
    parent_company_source_id VARCHAR(128)   NULL,
    source_downloaded        TINYINT(1)     NOT NULL DEFAULT 0,
    ownership_state          VARCHAR(32)    NOT NULL DEFAULT 'EXTERNAL_PRIMARY',
    record_origin            VARCHAR(16)    NOT NULL DEFAULT 'IMPORTED',
    source_synced_at         DATETIME(6)    NOT NULL,
    attributes_json          JSON           NULL,
    version                  BIGINT         NOT NULL DEFAULT 0,
    created_by               CHAR(36)       NULL,
    updated_by               CHAR(36)       NULL,
    created_at               DATETIME(6)    NOT NULL,
    updated_at               DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_purchase_return_no UNIQUE (tenant_id, purchase_return_no),
    CONSTRAINT uk_erp_purchase_return_source UNIQUE (tenant_id, source_return_id),
    CONSTRAINT fk_erp_purchase_return_supplier FOREIGN KEY (supplier_id) REFERENCES erp_supplier (id),
    CONSTRAINT fk_erp_purchase_return_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_warehouse (id),
    KEY idx_erp_purchase_return_status (tenant_id, internal_status, source_created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP采购退货单主表';

CREATE TABLE erp_purchase_return_line (
    id                         CHAR(36)       NOT NULL,
    tenant_id                  VARCHAR(64)    NOT NULL,
    purchase_return_id         CHAR(36)       NOT NULL,
    source_line_id             VARCHAR(128)   NOT NULL,
    spu_id                     CHAR(36)       NULL,
    sku_id                     CHAR(36)       NULL,
    purchase_order_line_id     CHAR(36)       NULL,
    source_goods_id            VARCHAR(128)   NULL,
    source_goods_code          VARCHAR(128)   NULL,
    source_goods_name          VARCHAR(240)   NULL,
    source_options_id          VARCHAR(128)   NULL,
    source_options_goods_code  VARCHAR(128)   NULL,
    options_summary            VARCHAR(500)   NULL,
    requested_quantity         DECIMAL(20,6)  NOT NULL DEFAULT 0,
    confirmed_quantity         DECIMAL(20,6)  NOT NULL DEFAULT 0,
    return_price               DECIMAL(20,6)  NOT NULL DEFAULT 0,
    confirmed_price            DECIMAL(20,6)  NOT NULL DEFAULT 0,
    return_unit_code           VARCHAR(40)    NULL,
    return_unit_name           VARCHAR(80)    NULL,
    return_unit_quantity       DECIMAL(20,6)  NOT NULL DEFAULT 0,
    confirmed_unit_quantity    DECIMAL(20,6)  NOT NULL DEFAULT 0,
    conversion_number          DECIMAL(20,6)  NOT NULL DEFAULT 0,
    amount                     DECIMAL(20,6)  NOT NULL DEFAULT 0,
    cost_price                 DECIMAL(20,6)  NOT NULL DEFAULT 0,
    purchase_order_no          VARCHAR(128)   NULL,
    category_name_snapshot     VARCHAR(160)   NULL,
    brand_name_snapshot        VARCHAR(160)   NULL,
    remark                     VARCHAR(1000)  NULL,
    attributes_json            JSON           NULL,
    created_at                 DATETIME(6)    NOT NULL,
    updated_at                 DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_purchase_return_line UNIQUE (tenant_id, purchase_return_id, source_line_id),
    CONSTRAINT fk_erp_purchase_return_line_return FOREIGN KEY (purchase_return_id) REFERENCES erp_purchase_return (id),
    CONSTRAINT fk_erp_purchase_return_line_spu FOREIGN KEY (spu_id) REFERENCES erp_product_spu (id),
    CONSTRAINT fk_erp_purchase_return_line_sku FOREIGN KEY (sku_id) REFERENCES erp_product_sku (id),
    CONSTRAINT fk_erp_purchase_return_line_purchase FOREIGN KEY (purchase_order_line_id) REFERENCES erp_purchase_order_line (id),
    KEY idx_erp_purchase_return_line_goods (tenant_id, source_goods_code, source_options_goods_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP采购退货单明细';

CREATE TABLE erp_warehousing_receipt (
    id                       CHAR(36)       NOT NULL,
    tenant_id                VARCHAR(64)    NOT NULL,
    warehousing_no           VARCHAR(128)   NOT NULL,
    source_warehousing_id    VARCHAR(128)   NULL,
    warehouse_id             CHAR(36)       NULL,
    supplier_id              CHAR(36)       NULL,
    warehouse_name_snapshot  VARCHAR(200)   NULL,
    supplier_name_snapshot   VARCHAR(200)   NULL,
    source_type_id           VARCHAR(32)    NULL,
    source_type_name         VARCHAR(100)   NULL,
    source_status            VARCHAR(32)    NULL,
    source_status_name       VARCHAR(80)    NULL,
    internal_status          VARCHAR(24)    NOT NULL DEFAULT 'DRAFT',
    staff_name               VARCHAR(120)   NULL,
    client_source_id         VARCHAR(128)   NULL,
    account_source_id        VARCHAR(128)   NULL,
    collaborator_source_id   VARCHAR(128)   NULL,
    collaborator_name        VARCHAR(200)   NULL,
    logistics_source_id      VARCHAR(128)   NULL,
    express_number           VARCHAR(160)   NULL,
    storage_at               DATETIME(6)    NULL,
    source_created_at        DATETIME(6)    NULL,
    source_updated_at        DATETIME(6)    NULL,
    freight_amount           DECIMAL(20,6)  NOT NULL DEFAULT 0,
    total_amount             DECIMAL(20,6)  NOT NULL DEFAULT 0,
    cost_amount              DECIMAL(20,6)  NOT NULL DEFAULT 0,
    source_api_flag          TINYINT(1)     NOT NULL DEFAULT 0,
    split_type               VARCHAR(32)    NULL,
    remark                   VARCHAR(1000)  NULL,
    ownership_state          VARCHAR(32)    NOT NULL DEFAULT 'EXTERNAL_PRIMARY',
    record_origin            VARCHAR(16)    NOT NULL DEFAULT 'IMPORTED',
    source_synced_at         DATETIME(6)    NOT NULL,
    attributes_json          JSON           NULL,
    version                  BIGINT         NOT NULL DEFAULT 0,
    created_by               CHAR(36)       NULL,
    updated_by               CHAR(36)       NULL,
    created_at               DATETIME(6)    NOT NULL,
    updated_at               DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_warehousing_no UNIQUE (tenant_id, warehousing_no),
    CONSTRAINT uk_erp_warehousing_source UNIQUE (tenant_id, source_warehousing_id),
    CONSTRAINT fk_erp_warehousing_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_warehouse (id),
    CONSTRAINT fk_erp_warehousing_supplier FOREIGN KEY (supplier_id) REFERENCES erp_supplier (id),
    KEY idx_erp_warehousing_status (tenant_id, internal_status, storage_at),
    KEY idx_erp_warehousing_warehouse (tenant_id, warehouse_id, storage_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP入库单主表';

CREATE TABLE erp_warehousing_receipt_line (
    id                         CHAR(36)       NOT NULL,
    tenant_id                  VARCHAR(64)    NOT NULL,
    warehousing_receipt_id     CHAR(36)       NOT NULL,
    source_line_id             VARCHAR(128)   NOT NULL,
    spu_id                     CHAR(36)       NULL,
    sku_id                     CHAR(36)       NULL,
    source_goods_id            VARCHAR(128)   NULL,
    source_goods_code          VARCHAR(128)   NULL,
    source_goods_name          VARCHAR(240)   NULL,
    source_options_id          VARCHAR(128)   NULL,
    source_options_goods_code  VARCHAR(128)   NULL,
    options_summary            VARCHAR(500)   NULL,
    base_quantity              DECIMAL(20,6)  NOT NULL DEFAULT 0,
    unit_quantity              DECIMAL(20,6)  NOT NULL DEFAULT 0,
    unit_code                  VARCHAR(40)    NULL,
    unit_name                  VARCHAR(80)    NULL,
    conversion_number          DECIMAL(20,6)  NOT NULL DEFAULT 0,
    cost_price                 DECIMAL(20,6)  NOT NULL DEFAULT 0,
    unit_cost_price            DECIMAL(20,6)  NOT NULL DEFAULT 0,
    purchase_price             DECIMAL(20,6)  NOT NULL DEFAULT 0,
    wholesale_price            DECIMAL(20,6)  NOT NULL DEFAULT 0,
    allocation                 VARCHAR(200)   NULL,
    barcode                    VARCHAR(160)   NULL,
    goods_model                VARCHAR(160)   NULL,
    source_real_quantity       DECIMAL(20,6)  NULL,
    source_available_quantity  DECIMAL(20,6)  NULL,
    collaborator_source_id     VARCHAR(128)   NULL,
    collaborator_name          VARCHAR(200)   NULL,
    remark                     VARCHAR(1000)  NULL,
    attributes_json            JSON           NULL,
    created_at                 DATETIME(6)    NOT NULL,
    updated_at                 DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_warehousing_line UNIQUE (tenant_id, warehousing_receipt_id, source_line_id),
    CONSTRAINT fk_erp_warehousing_line_receipt FOREIGN KEY (warehousing_receipt_id) REFERENCES erp_warehousing_receipt (id),
    CONSTRAINT fk_erp_warehousing_line_spu FOREIGN KEY (spu_id) REFERENCES erp_product_spu (id),
    CONSTRAINT fk_erp_warehousing_line_sku FOREIGN KEY (sku_id) REFERENCES erp_product_sku (id),
    KEY idx_erp_warehousing_line_goods (tenant_id, source_goods_code, source_options_goods_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP入库单明细';

CREATE TABLE erp_warehousing_purchase_link (
    id                       CHAR(36)      NOT NULL,
    tenant_id                VARCHAR(64)   NOT NULL,
    warehousing_receipt_id   CHAR(36)      NOT NULL,
    purchase_order_id        CHAR(36)      NULL,
    source_purchase_id       VARCHAR(128)  NULL,
    purchase_order_no        VARCHAR(128)  NOT NULL,
    created_at               DATETIME(6)   NOT NULL,
    updated_at               DATETIME(6)   NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_warehousing_purchase_link UNIQUE (tenant_id, warehousing_receipt_id, purchase_order_no),
    CONSTRAINT fk_erp_warehousing_purchase_receipt FOREIGN KEY (warehousing_receipt_id) REFERENCES erp_warehousing_receipt (id),
    CONSTRAINT fk_erp_warehousing_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES erp_purchase_order (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP入库单与采购单关系';

CREATE TABLE erp_inventory_balance (
    id                         CHAR(36)       NOT NULL,
    tenant_id                  VARCHAR(64)    NOT NULL,
    warehouse_id               CHAR(36)       NULL,
    spu_id                     CHAR(36)       NULL,
    sku_id                     CHAR(36)       NULL,
    source_warehouse_key       VARCHAR(160)   NOT NULL,
    source_warehouse_guid      VARCHAR(128)   NULL,
    source_warehouse_code      VARCHAR(128)   NULL,
    source_warehouse_name      VARCHAR(200)   NULL,
    source_product_key         VARCHAR(160)   NOT NULL,
    source_goods_guid          VARCHAR(128)   NULL,
    source_goods_code          VARCHAR(128)   NULL,
    source_goods_name          VARCHAR(240)   NULL,
    source_variant_key         VARCHAR(320)   NOT NULL,
    first_option_guid          VARCHAR(128)   NULL,
    first_option_code          VARCHAR(128)   NULL,
    first_option_name          VARCHAR(160)   NULL,
    second_option_guid         VARCHAR(128)   NULL,
    second_option_code         VARCHAR(128)   NULL,
    second_option_name         VARCHAR(160)   NULL,
    real_quantity              DECIMAL(20,6)  NOT NULL DEFAULT 0,
    available_quantity         DECIMAL(20,6)  NOT NULL DEFAULT 0,
    reserved_quantity          DECIMAL(20,6)  NOT NULL DEFAULT 0,
    in_transit_quantity        DECIMAL(20,6)  NOT NULL DEFAULT 0,
    calculation_origin         VARCHAR(32)    NOT NULL DEFAULT 'DHB_SNAPSHOT',
    source_synced_at           DATETIME(6)    NOT NULL,
    attributes_json            JSON           NULL,
    version                    BIGINT         NOT NULL DEFAULT 0,
    created_at                 DATETIME(6)    NOT NULL,
    updated_at                 DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_erp_inventory_balance UNIQUE
        (tenant_id, source_warehouse_key, source_product_key, source_variant_key),
    CONSTRAINT fk_erp_inventory_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_warehouse (id),
    CONSTRAINT fk_erp_inventory_spu FOREIGN KEY (spu_id) REFERENCES erp_product_spu (id),
    CONSTRAINT fk_erp_inventory_sku FOREIGN KEY (sku_id) REFERENCES erp_product_sku (id),
    KEY idx_erp_inventory_goods (tenant_id, source_goods_code, source_variant_key),
    KEY idx_erp_inventory_warehouse (tenant_id, warehouse_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP库存余额快照';
