-- 采购订单按入库仓库及独立动作授权。
SET @app=(SELECT id FROM iam_application WHERE app_code='SUPPLY_CHAIN');
SET @page=(SELECT resource_id FROM iam_resource_ui WHERE route_key='supply.erp.procurement.orders');
INSERT INTO iam_resource(id,application_id,parent_id,resource_code,resource_type,permission_code,display_name,sort_order,status,created_at,updated_at) VALUES(UUID_TO_BIN('8ac4b57e-7cf9-521e-a7b3-1243777eccc7'),@app,@page,'SUPPLY_CHAIN.ACTION.ERP.PROCUREMENT.READ','BUTTON','erp:procurement:read','查看采购订单',140,'ACTIVE',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
INSERT INTO iam_package_resource(package_version_id,resource_id,created_at) SELECT package_version_id,UUID_TO_BIN('8ac4b57e-7cf9-521e-a7b3-1243777eccc7'),UTC_TIMESTAMP(6) FROM iam_package_resource WHERE resource_id=@page;
INSERT INTO iam_resource(id,application_id,parent_id,resource_code,resource_type,permission_code,display_name,sort_order,status,created_at,updated_at) VALUES(UUID_TO_BIN('871a48c3-b560-53dc-8ae3-160a1bbf4296'),@app,@page,'SUPPLY_CHAIN.ACTION.ERP.PROCUREMENT.CREATE','BUTTON','erp:procurement:create','新增采购订单',141,'ACTIVE',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
INSERT INTO iam_package_resource(package_version_id,resource_id,created_at) SELECT package_version_id,UUID_TO_BIN('871a48c3-b560-53dc-8ae3-160a1bbf4296'),UTC_TIMESTAMP(6) FROM iam_package_resource WHERE resource_id=@page;
INSERT INTO iam_resource(id,application_id,parent_id,resource_code,resource_type,permission_code,display_name,sort_order,status,created_at,updated_at) VALUES(UUID_TO_BIN('bbfcc3e4-f9c2-5263-8e95-ba86f295eb09'),@app,@page,'SUPPLY_CHAIN.ACTION.ERP.PROCUREMENT.UPDATE','BUTTON','erp:procurement:update','编辑采购订单',142,'ACTIVE',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
INSERT INTO iam_package_resource(package_version_id,resource_id,created_at) SELECT package_version_id,UUID_TO_BIN('bbfcc3e4-f9c2-5263-8e95-ba86f295eb09'),UTC_TIMESTAMP(6) FROM iam_package_resource WHERE resource_id=@page;
INSERT INTO iam_resource(id,application_id,parent_id,resource_code,resource_type,permission_code,display_name,sort_order,status,created_at,updated_at) VALUES(UUID_TO_BIN('c3c25bfa-8497-5f8a-9f86-8f3b75de85b5'),@app,@page,'SUPPLY_CHAIN.ACTION.ERP.PROCUREMENT.DELETE','BUTTON','erp:procurement:delete','删除采购订单',143,'ACTIVE',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
INSERT INTO iam_package_resource(package_version_id,resource_id,created_at) SELECT package_version_id,UUID_TO_BIN('c3c25bfa-8497-5f8a-9f86-8f3b75de85b5'),UTC_TIMESTAMP(6) FROM iam_package_resource WHERE resource_id=@page;
