package com.rigour.order.api.v1.model;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

/** 销售订单详情。 */
public record SalesOrderDetailView(
        Long id,
        String orderNo,
        String sourceSystemCode,
        String sourceOrderNo,
        String sourceStatusCode,
        String sourceCreatorId,
        String sourceCreatorStaffCode,
        String sourceCreatorName,
        String dataQualityStatusCode,
        String dataQualityMessage,
        Long customerId,
        String customerCodeSnapshot,
        String customerNameSnapshot,
        String contactNameSnapshot,
        String contactPhoneSnapshot,
        String regionCode,
        String regionName,
        String ownerSalesUserId,
        String ownerSalesName,
        String ownerEmployeeCode,
        String ownerEmployeeNameSnapshot,
        Instant orderDate,
        Instant paymentTime,
        Instant shipmentTime,
        String shipmentStatusCode,
        String orderStatusCode,
        String orderTypeCode,
        String paymentMethodCode,
        String paymentStatusCode,
        String outboundStatusCode,
        BigDecimal totalQuantity,
        BigDecimal originalAmount,
        BigDecimal discountRate,
        BigDecimal discountAmount,
        BigDecimal payableAmount,
        BigDecimal paidAmount,
        BigDecimal unpaidAmount,
        String remark,
        Integer revision,
        String createdBy,
        Instant createdTime,
        String updatedBy,
        Instant updatedTime,
        List<String> paymentVoucherKeys,
        List<FundDocumentAttachmentView> paymentAttachments,
        List<SalesOrderLineView> lines) {
    public SalesOrderDetailView {
        paymentVoucherKeys = paymentVoucherKeys == null ? List.of() : List.copyOf(paymentVoucherKeys);
        paymentAttachments = paymentAttachments == null ? List.of() : List.copyOf(paymentAttachments);
        lines = lines == null ? List.of() : List.copyOf(lines);
    }

    public SalesOrderDetailView(Long id, String orderNo, String sourceSystemCode, String sourceOrderNo,
                                String sourceStatusCode, String sourceCreatorId,
                                String sourceCreatorStaffCode, String sourceCreatorName,
                                String dataQualityStatusCode, String dataQualityMessage,
                                Long customerId, String customerCodeSnapshot,
                                String customerNameSnapshot, String contactNameSnapshot,
                                String contactPhoneSnapshot, String regionCode,
                                String ownerSalesUserId, String ownerSalesName,
                                String ownerEmployeeCode, String ownerEmployeeNameSnapshot,
                                Instant orderDate, Instant paymentTime,
                                Instant shipmentTime, String shipmentStatusCode,
                                String orderStatusCode, String orderTypeCode,
                                String paymentMethodCode, String paymentStatusCode,
                                String outboundStatusCode, BigDecimal totalQuantity,
                                BigDecimal originalAmount, BigDecimal discountRate,
                                BigDecimal discountAmount, BigDecimal payableAmount,
                                BigDecimal paidAmount, BigDecimal unpaidAmount,
                                String remark, Integer revision, String createdBy,
                                Instant createdTime, String updatedBy, Instant updatedTime,
                                List<String> paymentVoucherKeys,
                                List<FundDocumentAttachmentView> paymentAttachments,
                                List<SalesOrderLineView> lines) {
        this(id, orderNo, sourceSystemCode, sourceOrderNo, sourceStatusCode,
                sourceCreatorId, sourceCreatorStaffCode, sourceCreatorName,
                dataQualityStatusCode, dataQualityMessage, customerId,
                customerCodeSnapshot, customerNameSnapshot, contactNameSnapshot,
                contactPhoneSnapshot, regionCode, null, ownerSalesUserId,
                ownerSalesName, ownerEmployeeCode, ownerEmployeeNameSnapshot,
                orderDate, paymentTime, shipmentTime, shipmentStatusCode,
                orderStatusCode, orderTypeCode, paymentMethodCode,
                paymentStatusCode, outboundStatusCode, totalQuantity,
                originalAmount, discountRate, discountAmount, payableAmount,
                paidAmount, unpaidAmount, remark, revision, createdBy,
                createdTime, updatedBy, updatedTime, paymentVoucherKeys,
                paymentAttachments, lines);
    }

    public SalesOrderDetailView(Long id, String orderNo, String sourceSystemCode, String sourceOrderNo,
                                String sourceStatusCode, String sourceCreatorId,
                                String sourceCreatorStaffCode, String sourceCreatorName,
                                String dataQualityStatusCode, String dataQualityMessage,
                                Long customerId, String customerCodeSnapshot,
                                String customerNameSnapshot, String contactNameSnapshot,
                                String contactPhoneSnapshot, String regionCode,
                                String ownerSalesUserId, String ownerSalesName,
                                String ownerEmployeeCode, String ownerEmployeeNameSnapshot,
                                Instant orderDate, Instant paymentTime,
                                Instant shipmentTime, String shipmentStatusCode,
                                String orderStatusCode, String orderTypeCode,
                                String paymentMethodCode, String paymentStatusCode,
                                String outboundStatusCode, BigDecimal totalQuantity,
                                BigDecimal originalAmount, BigDecimal discountRate,
                                BigDecimal discountAmount, BigDecimal payableAmount,
                                BigDecimal paidAmount, BigDecimal unpaidAmount,
                                String remark, Integer revision, String createdBy,
                                Instant createdTime, String updatedBy, Instant updatedTime,
                                List<SalesOrderLineView> lines) {
        this(id, orderNo, sourceSystemCode, sourceOrderNo, sourceStatusCode,
                sourceCreatorId, sourceCreatorStaffCode, sourceCreatorName,
                dataQualityStatusCode, dataQualityMessage, customerId,
                customerCodeSnapshot, customerNameSnapshot, contactNameSnapshot,
                contactPhoneSnapshot, regionCode, null, ownerSalesUserId,
                ownerSalesName, ownerEmployeeCode, ownerEmployeeNameSnapshot,
                orderDate, paymentTime, shipmentTime, shipmentStatusCode,
                orderStatusCode, orderTypeCode, paymentMethodCode,
                paymentStatusCode, outboundStatusCode, totalQuantity,
                originalAmount, discountRate, discountAmount, payableAmount,
                paidAmount, unpaidAmount, remark, revision, createdBy,
                createdTime, updatedBy, updatedTime, List.of(), List.of(), lines);
    }

    public SalesOrderDetailView(Long id, String orderNo, String sourceSystemCode, String sourceOrderNo,
                                String sourceStatusCode, String sourceCreatorId,
                                String sourceCreatorStaffCode, String sourceCreatorName,
                                Long customerId, String customerCodeSnapshot,
                                String customerNameSnapshot, String contactNameSnapshot,
                                String contactPhoneSnapshot, String regionCode,
                                String ownerSalesUserId, String ownerSalesName,
                                String ownerEmployeeCode, String ownerEmployeeNameSnapshot,
                                Instant orderDate, Instant paymentTime,
                                Instant shipmentTime, String shipmentStatusCode,
                                String orderStatusCode, String orderTypeCode,
                                String paymentMethodCode, String paymentStatusCode,
                                String outboundStatusCode, BigDecimal totalQuantity,
                                BigDecimal originalAmount, BigDecimal discountRate,
                                BigDecimal discountAmount, BigDecimal payableAmount,
                                BigDecimal paidAmount, BigDecimal unpaidAmount,
                                String remark, Integer revision, String createdBy,
                                Instant createdTime, String updatedBy, Instant updatedTime,
                                List<SalesOrderLineView> lines) {
        this(id, orderNo, sourceSystemCode, sourceOrderNo, sourceStatusCode,
                sourceCreatorId, sourceCreatorStaffCode, sourceCreatorName,
                null, null, customerId, customerCodeSnapshot, customerNameSnapshot,
                contactNameSnapshot, contactPhoneSnapshot, regionCode, ownerSalesUserId,
                ownerSalesName, ownerEmployeeCode, ownerEmployeeNameSnapshot,
                orderDate, paymentTime, shipmentTime, shipmentStatusCode,
                orderStatusCode, orderTypeCode, paymentMethodCode, paymentStatusCode,
                outboundStatusCode, totalQuantity, originalAmount, discountRate,
                discountAmount, payableAmount, paidAmount, unpaidAmount, remark,
                revision, createdBy, createdTime, updatedBy, updatedTime, lines);
    }

    public SalesOrderDetailView(Long id, String orderNo, String sourceSystemCode, String sourceOrderNo,
                                Long customerId, String customerCodeSnapshot,
                                String customerNameSnapshot, String contactNameSnapshot,
                                String contactPhoneSnapshot, String regionCode,
                                String ownerSalesUserId, String ownerSalesName,
                                String ownerEmployeeCode, String ownerEmployeeNameSnapshot,
                                Instant orderDate, Instant paymentTime,
                                Instant shipmentTime, String orderStatusCode,
                                String orderTypeCode, String paymentMethodCode,
                                String paymentStatusCode, String outboundStatusCode,
                                BigDecimal totalQuantity, BigDecimal originalAmount,
                                BigDecimal discountRate, BigDecimal discountAmount,
                                BigDecimal payableAmount, BigDecimal paidAmount,
                                BigDecimal unpaidAmount, String remark, Integer revision,
                                String createdBy, Instant createdTime, String updatedBy,
                                Instant updatedTime, List<SalesOrderLineView> lines) {
        this(id, orderNo, sourceSystemCode, sourceOrderNo, null, null, null, null,
                null, null,
                customerId, customerCodeSnapshot, customerNameSnapshot,
                contactNameSnapshot, contactPhoneSnapshot, regionCode,
                ownerSalesUserId, ownerSalesName, ownerEmployeeCode,
                ownerEmployeeNameSnapshot, orderDate, paymentTime, shipmentTime,
                null, orderStatusCode, orderTypeCode, paymentMethodCode,
                paymentStatusCode, outboundStatusCode, totalQuantity,
                originalAmount, discountRate, discountAmount, payableAmount,
                paidAmount, unpaidAmount, remark, revision, createdBy,
                createdTime, updatedBy, updatedTime, lines);
    }

    public SalesOrderDetailView(Long id, String orderNo, String sourceSystemCode, String sourceOrderNo,
                                String sourceStatusCode, Long customerId,
                                String customerCodeSnapshot, String customerNameSnapshot,
                                String contactNameSnapshot, String contactPhoneSnapshot,
                                String regionCode, String ownerSalesUserId,
                                String ownerSalesName, String ownerEmployeeCode,
                                String ownerEmployeeNameSnapshot, Instant orderDate,
                                Instant paymentTime, Instant shipmentTime,
                                String orderStatusCode, String orderTypeCode,
                                String paymentMethodCode, String paymentStatusCode,
                                String outboundStatusCode, BigDecimal totalQuantity,
                                BigDecimal originalAmount, BigDecimal discountRate,
                                BigDecimal discountAmount, BigDecimal payableAmount,
                                BigDecimal paidAmount, BigDecimal unpaidAmount,
                                String remark, Integer revision, String createdBy,
                                Instant createdTime, String updatedBy, Instant updatedTime,
                                List<SalesOrderLineView> lines) {
        this(id, orderNo, sourceSystemCode, sourceOrderNo, sourceStatusCode, null, null, null,
                null, null,
                customerId, customerCodeSnapshot, customerNameSnapshot,
                contactNameSnapshot, contactPhoneSnapshot, regionCode,
                ownerSalesUserId, ownerSalesName, ownerEmployeeCode,
                ownerEmployeeNameSnapshot, orderDate, paymentTime, shipmentTime,
                null, orderStatusCode, orderTypeCode, paymentMethodCode,
                paymentStatusCode, outboundStatusCode, totalQuantity,
                originalAmount, discountRate, discountAmount, payableAmount,
                paidAmount, unpaidAmount, remark, revision, createdBy,
                createdTime, updatedBy, updatedTime, lines);
    }

    public SalesOrderDetailView(Long id, String orderNo, Long customerId,
                                String customerCodeSnapshot, String customerNameSnapshot,
                                String contactNameSnapshot, String contactPhoneSnapshot,
                                String regionCode, String ownerSalesUserId,
                                String ownerSalesName, String ownerEmployeeCode,
                                String ownerEmployeeNameSnapshot, Instant orderDate,
                                String orderStatusCode, String orderTypeCode,
                                String paymentMethodCode, String paymentStatusCode,
                                String outboundStatusCode, BigDecimal totalQuantity,
                                BigDecimal originalAmount, BigDecimal discountRate,
                                BigDecimal discountAmount, BigDecimal payableAmount,
                                BigDecimal paidAmount, BigDecimal unpaidAmount,
                                String remark, Integer revision, String createdBy,
                                Instant createdTime, String updatedBy, Instant updatedTime,
                                List<SalesOrderLineView> lines) {
        this(id, orderNo, null, null, null, null, null, null, null, null, customerId,
                customerCodeSnapshot, customerNameSnapshot, contactNameSnapshot,
                contactPhoneSnapshot, regionCode, ownerSalesUserId, ownerSalesName,
                ownerEmployeeCode, ownerEmployeeNameSnapshot, orderDate, null, null,
                null, orderStatusCode, orderTypeCode, paymentMethodCode,
                paymentStatusCode, outboundStatusCode, totalQuantity,
                originalAmount, discountRate, discountAmount, payableAmount,
                paidAmount, unpaidAmount, remark, revision, createdBy,
                createdTime, updatedBy, updatedTime, lines);
    }

    public SalesOrderDetailView(Long id, String orderNo, Long customerId,
                                String customerCodeSnapshot, String customerNameSnapshot,
                                String contactNameSnapshot, String contactPhoneSnapshot,
                                String regionCode, String ownerSalesUserId,
                                String ownerSalesName, Instant orderDate,
                                String orderStatusCode, String orderTypeCode,
                                String paymentMethodCode, String paymentStatusCode,
                                String outboundStatusCode, BigDecimal totalQuantity,
                                BigDecimal originalAmount, BigDecimal discountRate,
                                BigDecimal discountAmount, BigDecimal payableAmount,
                                BigDecimal paidAmount, BigDecimal unpaidAmount,
                                String remark, Integer revision, String createdBy,
                                Instant createdTime, String updatedBy, Instant updatedTime,
                                List<SalesOrderLineView> lines) {
        this(id, orderNo, null, null, null, null, null, null, null, null, customerId,
                customerCodeSnapshot, customerNameSnapshot, contactNameSnapshot,
                contactPhoneSnapshot, regionCode, ownerSalesUserId, ownerSalesName,
                null, null, orderDate, null, null, null, orderStatusCode,
                orderTypeCode, paymentMethodCode, paymentStatusCode,
                outboundStatusCode, totalQuantity, originalAmount, discountRate,
                discountAmount, payableAmount, paidAmount, unpaidAmount, remark,
                revision, createdBy, createdTime, updatedBy, updatedTime, lines);
    }
}
