package com.rigour.analytics.infrastructure.persistence.scope;

import java.util.*;

/** BI v1 固定源数据契约，与各领域最小列目录及本地迁移保持一致。 */
public final class BiSourceDatasets {
    private BiSourceDatasets() {}

    public record Column(String name, boolean binary) {}

    public record Dataset(
            String source,
            String code,
            String table,
            boolean binaryTenant,
            boolean binaryKey,
            List<Column> columns) {}

    public static final List<Dataset> ALL =
            List.of(
                    new Dataset(
                            "SALES",
                            "SALES_SUBMITTED_VISIT",
                            "bi_source_sales_sales_submitted_visit",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("tenant_id", true),
                                    new Column("store_id", true),
                                    new Column("city_name", false),
                                    new Column("submitted_at", false),
                                    new Column("review_status", false),
                                    new Column("salesperson_id", true),
                                    new Column("owner_staff_code", false),
                                    new Column("customer_id", false),
                                    new Column("customer_code", false))),
                    new Dataset(
                            "HR",
                            "HR_EMPLOYEE",
                            "bi_source_hr_hr_employee",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("employee_code", false),
                                    new Column("employee_name", false),
                                    new Column("employment_status", false),
                                    new Column("city_name", false),
                                    new Column("position_name", false),
                                    new Column("department_name", false),
                                    new Column("department_id", false),
                                    new Column("department_path", false),
                                    new Column("entry_date", false),
                                    new Column("leave_date", false))),
                    new Dataset(
                            "CRM",
                            "CRM_CONTACT",
                            "bi_source_crm_crm_contact",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("tenant_id", true),
                                    new Column("party_id", true),
                                    new Column("contact_name", false),
                                    new Column("phone", false),
                                    new Column("is_primary", false),
                                    new Column("status", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "CRM",
                            "CRM_CUSTOMER",
                            "bi_source_crm_crm_customer",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("customer_code", false),
                                    new Column("party_id", true),
                                    new Column("customer_name", false),
                                    new Column("customer_source_name", false),
                                    new Column("business_category_name", false),
                                    new Column("contact_name", false),
                                    new Column("contact_phone", false),
                                    new Column("customer_type_code", false),
                                    new Column("region_code", false),
                                    new Column("region_name", false),
                                    new Column("owner_sales_name", false),
                                    new Column("owner_employee_code", false),
                                    new Column("owner_employee_name_snapshot", false),
                                    new Column("status_code", false),
                                    new Column("source_system_code", false),
                                    new Column("source_document_no", false),
                                    new Column("business_created_at", false),
                                    new Column("business_created_by_id", false),
                                    new Column("business_created_by_name", false),
                                    new Column("business_creation_source", false),
                                    new Column("source_created_at", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "CRM",
                            "CRM_CUSTOMER_AREA",
                            "bi_source_crm_crm_customer_area",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("tenant_id", true),
                                    new Column("area_code", false),
                                    new Column("area_name", false),
                                    new Column("parent_area_code", false),
                                    new Column("status", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "CRM",
                            "CRM_CUSTOMER_POLICY",
                            "bi_source_crm_crm_customer_policy",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("tenant_id", true),
                                    new Column("party_id", true),
                                    new Column("payment_term_days", false),
                                    new Column("status", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "CRM",
                            "CRM_CUSTOMER_TYPE",
                            "bi_source_crm_crm_customer_type",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("tenant_id", true),
                                    new Column("type_code", false),
                                    new Column("type_name", false),
                                    new Column("status", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_INVENTORY_WAREHOUSE",
                            "bi_source_erp_erp_inventory_warehouse",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("warehouse_code", false),
                                    new Column("warehouse_name", false),
                                    new Column("region_code", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_PROCUREMENT_ORDER",
                            "bi_source_erp_erp_procurement_order",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("procurement_no", false),
                                    new Column("source_document_no", false),
                                    new Column("target_warehouse_id", false),
                                    new Column("status_code", false),
                                    new Column("expected_arrival_time", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_PROCUREMENT_ORDER_LINE",
                            "bi_source_erp_erp_procurement_order_line",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("procurement_order_id", false),
                                    new Column("product_id", false),
                                    new Column("product_variant_id", false),
                                    new Column("product_code_snapshot", false),
                                    new Column("variant_code_snapshot", false),
                                    new Column("product_name_snapshot", false),
                                    new Column("unit_code", false),
                                    new Column("quantity", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_PRODUCT",
                            "bi_source_erp_erp_product",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("product_code", false),
                                    new Column("product_name", false),
                                    new Column("category_id", false),
                                    new Column("brand_id", false),
                                    new Column("unit_code", false),
                                    new Column("shelf_status_code", false),
                                    new Column("submit_status_code", false),
                                    new Column("source_system_code", false),
                                    new Column("source_document_no", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_PRODUCT_BRAND",
                            "bi_source_erp_erp_product_brand",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("brand_code", false),
                                    new Column("brand_name", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_PRODUCT_CATEGORY",
                            "bi_source_erp_erp_product_category",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("parent_id", false),
                                    new Column("category_code", false),
                                    new Column("category_name", false),
                                    new Column("category_level", false),
                                    new Column("ordinal", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_PRODUCT_VARIANT",
                            "bi_source_erp_erp_product_variant",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("product_id", false),
                                    new Column("variant_code", false),
                                    new Column("specification_snapshot", false),
                                    new Column("unit_code", false),
                                    new Column("purchase_price", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_STOCK_BALANCE",
                            "bi_source_erp_erp_stock_balance",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("warehouse_id", false),
                                    new Column("product_id", false),
                                    new Column("product_variant_id", false),
                                    new Column("available_quantity", false),
                                    new Column("locked_quantity", false),
                                    new Column("in_transit_quantity", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_STOCK_OUT_ORDER",
                            "bi_source_erp_erp_stock_out_order",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("stock_out_no", false),
                                    new Column("source_document_no", false),
                                    new Column("stock_out_type_code", false),
                                    new Column("warehouse_id", false),
                                    new Column("status_code", false),
                                    new Column("stock_out_time", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ERP",
                            "ERP_STOCK_OUT_ORDER_LINE",
                            "bi_source_erp_erp_stock_out_order_line",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("stock_out_order_id", false),
                                    new Column("product_id", false),
                                    new Column("product_variant_id", false),
                                    new Column("product_code_snapshot", false),
                                    new Column("variant_code_snapshot", false),
                                    new Column("product_name_snapshot", false),
                                    new Column("unit_code", false),
                                    new Column("quantity", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "INTEGRATION",
                            "INTEGRATION_FEISHU_IMPORT_BATCH",
                            "bi_source_integration_integration_feishu_import_batch",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("tenant_id", true),
                                    new Column("source_url", false),
                                    new Column("original_file_name", false),
                                    new Column("file_sha256", false),
                                    new Column("status", false),
                                    new Column("total_rows", false),
                                    new Column("created_at", false))),
                    new Dataset(
                            "INTEGRATION",
                            "INTEGRATION_FEISHU_IMPORT_RAW_ROW",
                            "bi_source_integration_integration_feishu_import_raw_row",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("batch_id", true),
                                    new Column("tenant_id", true),
                                    new Column("sheet_name", false),
                                    new Column("table_code", false),
                                    new Column("source_row_number", false),
                                    new Column("source_document_no", false),
                                    new Column("source_created_at", false),
                                    new Column("raw_row_hash", false),
                                    new Column("row_json", false),
                                    new Column("import_status", false),
                                    new Column("projection_status", false),
                                    new Column("error_code", false),
                                    new Column("created_at", false),
                                    new Column("updated_at", false))),
                    new Dataset(
                            "INTEGRATION",
                            "INTEGRATION_FEISHU_ONLINE_CAPTURE",
                            "bi_source_integration_integration_feishu_online_capture",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("tenant_id", true),
                                    new Column("source_id", false),
                                    new Column("source_name", false),
                                    new Column("source_url", false),
                                    new Column("started_at", false),
                                    new Column("completed_at", false),
                                    new Column("complete", false),
                                    new Column("filtered", false),
                                    new Column("checksum", false),
                                    new Column("record_count", false),
                                    new Column("page_count", false),
                                    new Column("payload_json", false))),
                    new Dataset(
                            "INTEGRATION",
                            "INTEGRATION_RAW_LANDING",
                            "bi_source_integration_integration_raw_landing",
                            true,
                            true,
                            List.of(
                                    new Column("id", true),
                                    new Column("tenant_id", true),
                                    new Column("source_system", false),
                                    new Column("source_object_type", false),
                                    new Column("source_id", false),
                                    new Column("received_at", false))),
                    new Dataset(
                            "ORDER",
                            "ORDER_PAYMENT_RECORD",
                            "bi_source_order_order_payment_record",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("payment_no", false),
                                    new Column("source_system_code", false),
                                    new Column("source_document_no", false),
                                    new Column("order_id", false),
                                    new Column("sales_order_no_snapshot", false),
                                    new Column("customer_id", false),
                                    new Column("customer_code_snapshot", false),
                                    new Column("customer_name_snapshot", false),
                                    new Column("collector_staff_code", false),
                                    new Column("collector_name_snapshot", false),
                                    new Column("payment_time", false),
                                    new Column("payment_method_code", false),
                                    new Column("paid_amount", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ORDER",
                            "ORDER_REFUND_RECORD",
                            "bi_source_order_order_refund_record",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("order_id", false),
                                    new Column("customer_id", false),
                                    new Column("customer_code_snapshot", false),
                                    new Column("customer_name_snapshot", false),
                                    new Column("refund_status_code", false),
                                    new Column("refund_amount", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))),
                    new Dataset(
                            "ORDER",
                            "ORDER_SALES_ORDER",
                            "bi_source_order_order_sales_order",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("order_no", false),
                                    new Column("source_system_code", false),
                                    new Column("source_order_no", false),
                                    new Column("customer_id", false),
                                    new Column("customer_code_snapshot", false),
                                    new Column("customer_name_snapshot", false),
                                    new Column("region_code", false),
                                    new Column("owner_sales_name", false),
                                    new Column("owner_employee_code", false),
                                    new Column("owner_employee_name_snapshot", false),
                                    new Column("order_date", false),
                                    new Column("order_status_code", false),
                                    new Column("order_type_code", false),
                                    new Column("payment_method_code", false),
                                    new Column("payment_status_code", false),
                                    new Column("outbound_status_code", false),
                                    new Column("total_quantity", false),
                                    new Column("discount_rate", false),
                                    new Column("discount_amount", false),
                                    new Column("payable_amount", false),
                                    new Column("paid_amount", false),
                                    new Column("unpaid_amount", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false),
                                    new Column("payment_time", false),
                                    new Column("shipment_time", false))),
                    new Dataset(
                            "ORDER",
                            "ORDER_SALES_ORDER_LINE",
                            "bi_source_order_order_sales_order_line",
                            false,
                            false,
                            List.of(
                                    new Column("id", false),
                                    new Column("tenant_id", false),
                                    new Column("order_id", false),
                                    new Column("product_id", false),
                                    new Column("product_variant_id", false),
                                    new Column("product_code_snapshot", false),
                                    new Column("sku_code_snapshot", false),
                                    new Column("product_name_snapshot", false),
                                    new Column("specification_snapshot", false),
                                    new Column("unit_code", false),
                                    new Column("quantity", false),
                                    new Column("unit_price", false),
                                    new Column("discount_rate", false),
                                    new Column("discount_amount", false),
                                    new Column("line_amount", false),
                                    new Column("created_time", false),
                                    new Column("updated_time", false),
                                    new Column("deleted", false))));
}
