#!/usr/bin/env bash

set -euo pipefail

# 仅创建领域 Schema 和两类数据库账号，不创建业务表。
# 默认在共享 DEV 服务器本机执行；生产环境必须使用明确的账号来源和密码管理方案。

mysql_host="${MYSQL_HOST:-127.0.0.1}"
mysql_port="${MYSQL_PORT:-3306}"
account_host="${RIGOUR_DB_ACCOUNT_HOST:-%}"
credential_file="${RIGOUR_DB_CREDENTIAL_FILE:-/opt/rigour-dev/domain-db.env}"
rotate_existing_passwords="${RIGOUR_DB_ROTATE_EXISTING_PASSWORDS:-false}"

services=(
  "crm|rigour_crm|rigour_crm_app|rigour_crm_migrator|CRM_DB_APP_PASSWORD|CRM_DB_MIGRATOR_PASSWORD"
  "erp|rigour_erp|rigour_erp_app|rigour_erp_migrator|ERP_DB_APP_PASSWORD|ERP_DB_MIGRATOR_PASSWORD"
  "order|rigour_order|rigour_order_app|rigour_order_migrator|ORDER_DB_APP_PASSWORD|ORDER_DB_MIGRATOR_PASSWORD"
  "sales_work|rigour_sales_work|rigour_sales_work_app|rigour_sales_work_migrator|SALES_WORK_DB_APP_PASSWORD|SALES_WORK_DB_MIGRATOR_PASSWORD"
  "business_settings|rigour_settings|rigour_settings_app|rigour_settings_mig|BUSINESS_SETTINGS_DB_APP_PASSWORD|BUSINESS_SETTINGS_DB_MIGRATOR_PASSWORD"
  "ai|rigour_ai|rigour_ai_app|rigour_ai_migrator|AI_DB_APP_PASSWORD|AI_DB_MIGRATOR_PASSWORD"
  "bi|rigour_bi|rigour_bi_app|rigour_bi_migrator|BI_DB_APP_PASSWORD|BI_DB_MIGRATOR_PASSWORD"
  "hr|rigour_hr|rigour_hr_app|rigour_hr_migrator|HR_DB_APP_PASSWORD|HR_DB_MIGRATOR_PASSWORD"
  "city|rigour_city|rigour_city_app|rigour_city_migrator|CITY_DB_APP_PASSWORD|CITY_DB_MIGRATOR_PASSWORD"
  "channel|rigour_channel|rigour_channel_app|rigour_channel_migrator|CHANNEL_DB_APP_PASSWORD|CHANNEL_DB_MIGRATOR_PASSWORD"
)

umask 077

mkdir -p "$(dirname "$credential_file")"
if [[ ! -e "$credential_file" ]]; then
  touch "$credential_file"
  chmod 600 "$credential_file"
fi

if [[ ! -r "$credential_file" || ! -w "$credential_file" ]]; then
  printf '凭据文件不可读写：%s\n' "$credential_file" >&2
  exit 1
fi

if ! grep -q '^# Rigour domain database credentials' "$credential_file"; then
  {
    printf '%s\n' '# Rigour domain database credentials'
    printf '%s\n' '# Generated by scripts/provision-domain-databases.sh; mode must remain 0600.'
  } >>"$credential_file"
fi

for service in "${services[@]}"; do
  IFS='|' read -r _ schema app_user migrator_user app_key migrator_key <<<"$service"
  if ! grep -q "^export ${app_key}=" "$credential_file"; then
    printf "export %s='%s'\n" "$app_key" "$(openssl rand -hex 32)" >>"$credential_file"
  fi
  if ! grep -q "^export ${migrator_key}=" "$credential_file"; then
    printf "export %s='%s'\n" "$migrator_key" "$(openssl rand -hex 32)" >>"$credential_file"
  fi
done

# shellcheck disable=SC1090
source "$credential_file"

admin_password="${MYSQL_ROOT_PASSWORD:-}"
if [[ -z "$admin_password" ]]; then
  read -r -s -p '请输入当前 MySQL 管理员密码（不会回显，也不会写入项目）: ' admin_password
  printf '\n'
fi

temporary_files=()
admin_cnf="$(mktemp)"
temporary_files+=("$admin_cnf")
cleanup() {
  for temporary_file in "${temporary_files[@]}"; do
    rm -f -- "$temporary_file"
  done
}
trap cleanup EXIT
chmod 600 "$admin_cnf"
{
  printf '%s\n' '[client]'
  printf 'host=%s\n' "$mysql_host"
  printf 'port=%s\n' "$mysql_port"
  printf '%s\n' 'user=root'
  printf 'password=%s\n' "$admin_password"
} >"$admin_cnf"

mysql_admin() {
  mysql --defaults-extra-file="$admin_cnf" --batch --skip-column-names "$@"
}

mysql_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\'/\'\'}"
  printf '%s' "$value"
}

for service in "${services[@]}"; do
  IFS='|' read -r service_key schema app_user migrator_user app_key migrator_key <<<"$service"
  app_password="${!app_key}"
  migrator_password="${!migrator_key}"
  schema_sql="$(mysql_escape "$schema")"
  app_user_sql="$(mysql_escape "$app_user")"
  migrator_user_sql="$(mysql_escape "$migrator_user")"
  account_host_sql="$(mysql_escape "$account_host")"
  app_password_sql="$(mysql_escape "$app_password")"
  migrator_password_sql="$(mysql_escape "$migrator_password")"

  mysql_admin <<SQL
CREATE DATABASE IF NOT EXISTS \`${schema_sql}\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${app_user_sql}'@'${account_host_sql}' IDENTIFIED BY '${app_password_sql}';
CREATE USER IF NOT EXISTS '${migrator_user_sql}'@'${account_host_sql}' IDENTIFIED BY '${migrator_password_sql}';
$(if [[ "$rotate_existing_passwords" == "true" ]]; then
  printf "ALTER USER '%s'@'%s' IDENTIFIED BY '%s';\n" "$app_user_sql" "$account_host_sql" "$app_password_sql"
  printf "ALTER USER '%s'@'%s' IDENTIFIED BY '%s';\n" "$migrator_user_sql" "$account_host_sql" "$migrator_password_sql"
fi)
GRANT SELECT, INSERT, UPDATE, DELETE
  ON \`${schema_sql}\`.* TO '${app_user_sql}'@'${account_host_sql}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
  ON \`${schema_sql}\`.* TO '${migrator_user_sql}'@'${account_host_sql}';
SQL

  printf '已处理 %-10s schema=%-20s app=%-28s migrator=%s\n' \
    "$service_key" "$schema" "$app_user" "$migrator_user"
done

mysql_admin -e 'FLUSH PRIVILEGES;'

printf '%s\n' '--- 领域 Schema 与账号验证 ---'
for service in "${services[@]}"; do
  IFS='|' read -r service_key schema app_user migrator_user app_key migrator_key <<<"$service"
  app_password="${!app_key}"
  migrator_password="${!migrator_key}"
  app_cnf="$(mktemp)"
  migrator_cnf="$(mktemp)"
  temporary_files+=("$app_cnf" "$migrator_cnf")
  chmod 600 "$app_cnf" "$migrator_cnf"
  {
    printf '%s\n' '[client]'
    printf 'host=%s\n' "$mysql_host"
    printf 'port=%s\n' "$mysql_port"
    printf 'user=%s\n' "$app_user"
    printf 'password=%s\n' "$app_password"
  } >"$app_cnf"
  {
    printf '%s\n' '[client]'
    printf 'host=%s\n' "$mysql_host"
    printf 'port=%s\n' "$mysql_port"
    printf 'user=%s\n' "$migrator_user"
    printf 'password=%s\n' "$migrator_password"
  } >"$migrator_cnf"

  app_identity="$(mysql --defaults-extra-file="$app_cnf" --batch --skip-column-names "$schema" -e 'SELECT CURRENT_USER();')"
  migrator_identity="$(mysql --defaults-extra-file="$migrator_cnf" --batch --skip-column-names "$schema" -e 'SELECT CURRENT_USER();')"
  table_count="$(mysql_admin --batch --skip-column-names -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$(mysql_escape "$schema")';")"
  printf '%-10s app=%s migrator=%s tables=%s\n' "$service_key" "$app_identity" "$migrator_identity" "$table_count"
  rm -f "$app_cnf" "$migrator_cnf"
done

printf '%s\n' "凭据已保存到 $credential_file（权限应为 0600）；不要提交 Git、写入 Nacos 或发送到聊天。"
