-- Analytics BI：销售订单行事实表。
--
-- 用于商品、规格和分类维度销售统计；Portal 请求只聚合本 BI 表。

CREATE TABLE bi_sales_order_line_fact (
    id                       BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                VARCHAR(64)    NOT NULL COMMENT '租户ID',
    order_line_id            BIGINT(20)     NOT NULL COMMENT '销售订单行ID',
    order_id                 BIGINT(20)     NOT NULL COMMENT '销售订单ID',
    order_no                 VARCHAR(50)    NULL COMMENT '销售订单号快照',
    source_system_code       VARCHAR(32)    NOT NULL DEFAULT 'MANUAL' COMMENT '来源系统编码',
    source_order_no          VARCHAR(80)    NULL COMMENT '来源平台订单号',
    customer_id              BIGINT(20)     NULL COMMENT 'CRM客户ID',
    customer_code            VARCHAR(50)    NULL COMMENT '客户编号快照',
    customer_name            VARCHAR(200)   NULL COMMENT '客户名称快照',
    customer_type_code       VARCHAR(64)    NULL COMMENT '客户类型编码快照',
    customer_status_code     VARCHAR(64)    NULL COMMENT '客户状态编码快照',
    region_code              VARCHAR(64)    NULL COMMENT '城市/区域编码快照',
    owner_staff_code         VARCHAR(50)    NULL COMMENT '归属销售员工编码快照',
    owner_staff_name         VARCHAR(100)   NULL COMMENT '归属销售姓名快照',
    order_date               DATETIME(6)    NOT NULL COMMENT '销售日期',
    payment_time             DATETIME(6)    NULL COMMENT '付款时间快照',
    shipment_time            DATETIME(6)    NULL COMMENT '发货时间快照',
    order_status_code        VARCHAR(64)    NULL COMMENT '订单状态编码',
    payment_status_code      VARCHAR(64)    NULL COMMENT '收款状态编码',
    outbound_status_code     VARCHAR(64)    NULL COMMENT '出库状态编码',
    order_type_code          VARCHAR(64)    NULL COMMENT '订单类型编码',
    product_id               BIGINT(20)     NULL COMMENT 'ERP商品ID',
    product_variant_id       BIGINT(20)     NULL COMMENT 'ERP商品规格ID',
    product_code             VARCHAR(50)    NULL COMMENT '商品编码快照',
    sku_code                 VARCHAR(50)    NULL COMMENT 'SKU编码快照',
    product_name             VARCHAR(200)   NULL COMMENT '商品名称快照',
    product_category_id      BIGINT(20)     NULL COMMENT '商品分类ID快照',
    product_category_code    VARCHAR(50)    NULL COMMENT '商品分类编码快照',
    product_category_name    VARCHAR(120)   NULL COMMENT '商品分类名称快照',
    specification_snapshot   VARCHAR(500)   NULL COMMENT '规格描述快照',
    unit_code                VARCHAR(64)    NULL COMMENT '单位编码快照',
    quantity                 DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '订货数量',
    unit_price               DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '成交单价',
    discount_rate            DECIMAL(10,4)  NULL COMMENT '折扣率',
    discount_amount          DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '折扣金额',
    line_amount              DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '订单行金额',
    source_updated_time      DATETIME(6)    NULL COMMENT '源数据更新时间水位',
    synced_time              DATETIME(6)    NOT NULL COMMENT '同步到BI时间',
    deleted                  INT            NOT NULL DEFAULT 0 COMMENT '源逻辑删除标识',
    created_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_bi_sales_order_line_fact_source (tenant_id, order_line_id),
    KEY idx_bi_sales_order_line_fact_date (tenant_id, order_date, deleted),
    KEY idx_bi_sales_order_line_fact_region (tenant_id, region_code, order_date),
    KEY idx_bi_sales_order_line_fact_owner (tenant_id, owner_staff_code, order_date),
    KEY idx_bi_sales_order_line_fact_customer (tenant_id, customer_id, order_date),
    KEY idx_bi_sales_order_line_fact_product (tenant_id, product_id, product_variant_id, order_date),
    KEY idx_bi_sales_order_line_fact_category (tenant_id, product_category_id, order_date),
    KEY idx_bi_sales_order_line_fact_source_sys (tenant_id, source_system_code, order_date),
    KEY idx_bi_sales_order_line_fact_updated (tenant_id, source_updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='BI销售订单行事实';
