-- ERP 自研业务基线：商品、采购、仓库库存、入库、出库、调拨。
-- 本迁移不继续扩展旧订货宝同步表；订货宝后续只通过 Integration 映射到这些业务表。
-- 表名、字段名统一 lower_snake_case；业务编码和状态值统一 UPPER_SNAKE_CASE；删除统一逻辑删。

CREATE TABLE erp_product_category (
    id                 BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id          VARCHAR(64)   NOT NULL COMMENT '租户ID',
    parent_id          BIGINT(20)    NULL COMMENT '父级分类ID',
    category_code      VARCHAR(50)   NOT NULL COMMENT '商品分类编码，由ERP编码规则生成',
    category_name      VARCHAR(120)  NOT NULL COMMENT '商品分类名称',
    category_level     INT           NOT NULL DEFAULT 1 COMMENT '分类层级，根节点为1',
    ordinal            INT           NOT NULL DEFAULT 0 COMMENT '展示顺序，数值越小越靠前',
    remark             VARCHAR(500)  NULL COMMENT '备注',
    revision           INT           NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by         VARCHAR(50)   NULL COMMENT '创建人',
    created_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by         VARCHAR(50)   NULL COMMENT '更新人',
    updated_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted            INT           NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_product_category_code (tenant_id, category_code),
    CONSTRAINT fk_erp_product_category_parent FOREIGN KEY (parent_id) REFERENCES erp_product_category (id),
    KEY idx_erp_product_category_parent (tenant_id, parent_id, deleted, ordinal)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP商品分类';

CREATE TABLE erp_product_brand (
    id                 BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id          VARCHAR(64)   NOT NULL COMMENT '租户ID',
    brand_code         VARCHAR(50)   NOT NULL COMMENT '商品品牌编码，由ERP编码规则生成',
    brand_name         VARCHAR(120)  NOT NULL COMMENT '商品品牌名称',
    remark             VARCHAR(500)  NULL COMMENT '备注',
    revision           INT           NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by         VARCHAR(50)   NULL COMMENT '创建人',
    created_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by         VARCHAR(50)   NULL COMMENT '更新人',
    updated_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted            INT           NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_product_brand_code (tenant_id, brand_code),
    KEY idx_erp_product_brand_name (tenant_id, brand_name, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP商品品牌';

CREATE TABLE erp_product_tag (
    id                 BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id          VARCHAR(64)   NOT NULL COMMENT '租户ID',
    tag_code           VARCHAR(50)   NOT NULL COMMENT '商品标签编码，由ERP编码规则生成',
    tag_name           VARCHAR(120)  NOT NULL COMMENT '商品标签名称',
    tag_type_code      VARCHAR(64)   NULL COMMENT '标签类型，关联 PRODUCT_TAG_TYPE 字典项',
    remark             VARCHAR(500)  NULL COMMENT '备注',
    revision           INT           NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by         VARCHAR(50)   NULL COMMENT '创建人',
    created_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by         VARCHAR(50)   NULL COMMENT '更新人',
    updated_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted            INT           NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_product_tag_code (tenant_id, tag_code),
    KEY idx_erp_product_tag_name (tenant_id, tag_name, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP商品标签';

CREATE TABLE erp_supplier_profile (
    id                 BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id          VARCHAR(64)   NOT NULL COMMENT '租户ID',
    supplier_code      VARCHAR(50)   NOT NULL COMMENT '供应商编码，由ERP编码规则生成',
    supplier_name      VARCHAR(200)  NOT NULL COMMENT '供应商名称',
    contact_name       VARCHAR(100)  NULL COMMENT '联系人',
    contact_phone      VARCHAR(50)   NULL COMMENT '联系电话',
    address            VARCHAR(1000) NULL COMMENT '供应商地址',
    bank_name          VARCHAR(100)  NULL COMMENT '开户银行',
    bank_account_no    VARCHAR(100)  NULL COMMENT '银行账号',
    status_code        VARCHAR(64)   NOT NULL DEFAULT 'ACTIVE' COMMENT '供应商状态，关联 SUPPLIER_STATUS 字典项',
    remark             VARCHAR(1000) NULL COMMENT '备注',
    revision           INT           NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by         VARCHAR(50)   NULL COMMENT '创建人',
    created_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by         VARCHAR(50)   NULL COMMENT '更新人',
    updated_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted            INT           NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_supplier_profile_code (tenant_id, supplier_code),
    KEY idx_erp_supplier_profile_name (tenant_id, supplier_name, deleted),
    KEY idx_erp_supplier_profile_status (tenant_id, status_code, deleted, updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP供应商档案';

CREATE TABLE erp_inventory_warehouse (
    id                 BIGINT(20)    NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id          VARCHAR(64)   NOT NULL COMMENT '租户ID',
    warehouse_code     VARCHAR(50)   NOT NULL COMMENT '仓库编码，由ERP编码规则生成',
    warehouse_name     VARCHAR(120)  NOT NULL COMMENT '仓库名称',
    region_code        VARCHAR(64)   NULL COMMENT '仓库归属地区，关联 REGION 字典项',
    warehouse_type_code VARCHAR(64)  NOT NULL DEFAULT 'CITY' COMMENT '仓库类型：DEFAULT/CITY/OTHER',
    default_flag       TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '是否默认仓库：0否，1是',
    address            VARCHAR(1000) NULL COMMENT '仓库地址',
    contact_name       VARCHAR(100)  NULL COMMENT '联系人',
    contact_phone      VARCHAR(50)   NULL COMMENT '联系电话',
    remark             VARCHAR(1000) NULL COMMENT '备注',
    revision           INT           NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by         VARCHAR(50)   NULL COMMENT '创建人',
    created_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by         VARCHAR(50)   NULL COMMENT '更新人',
    updated_time       DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted            INT           NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_inventory_warehouse_code (tenant_id, warehouse_code),
    KEY idx_erp_inventory_warehouse_region (tenant_id, region_code, deleted),
    KEY idx_erp_inventory_warehouse_default (tenant_id, default_flag, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP仓库';

CREATE TABLE erp_product (
    id                          BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                   VARCHAR(64)    NOT NULL COMMENT '租户ID',
    product_code                VARCHAR(50)    NOT NULL COMMENT '商品编码，由ERP编码规则生成',
    product_name                VARCHAR(200)   NULL COMMENT '商品名称；草稿允许暂为空，提交时由应用服务校验',
    category_id                 BIGINT(20)     NULL COMMENT '商品分类ID',
    brand_id                    BIGINT(20)     NULL COMMENT '商品品牌ID',
    product_specification       VARCHAR(500)   NULL COMMENT '商品规格说明',
    unit_code                   VARCHAR(64)    NULL COMMENT '商品单位，关联 PRODUCT_UNIT 字典项；草稿允许暂为空，提交时由应用服务校验',
    min_order_quantity          DECIMAL(24,6)  NULL COMMENT '起订量',
    order_multiple_flag         TINYINT(1)     NOT NULL DEFAULT 0 COMMENT '是否整倍订货：0否，1是',
    order_multiple_quantity     DECIMAL(24,6)  NULL COMMENT '整倍订货数量',
    sale_type_code              VARCHAR(64)    NOT NULL DEFAULT 'SPOT' COMMENT '售卖类型，关联 PRODUCT_SALE_TYPE 字典项',
    shelf_status_code           VARCHAR(64)    NOT NULL DEFAULT 'OFF_SHELF' COMMENT '上架状态，关联 PRODUCT_SHELF_STATUS 字典项',
    tag_codes_json              JSON           NULL COMMENT '商品标签编码数组，来源商品标签列表',
    limit_quantity              DECIMAL(24,6)  NULL COMMENT '限购量',
    default_warehouse_id        BIGINT(20)     NULL COMMENT '默认归属仓库ID',
    image_keys_json             JSON           NULL COMMENT '商品图片COS key数组，最多24张，区分主图和详情图',
    recommend_product_ids_json  JSON           NULL COMMENT '商品页关联推荐商品ID数组',
    submit_status_code          VARCHAR(64)    NOT NULL DEFAULT 'DRAFT' COMMENT '提交状态，关联 PRODUCT_SUBMIT_STATUS 字典项',
    remark                      VARCHAR(1000)  NULL COMMENT '商品备注',
    revision                    INT            NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by                  VARCHAR(50)    NULL COMMENT '创建人',
    created_time                DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by                  VARCHAR(50)    NULL COMMENT '更新人',
    updated_time                DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted                     INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_product_code (tenant_id, product_code),
    CONSTRAINT fk_erp_product_category FOREIGN KEY (category_id) REFERENCES erp_product_category (id),
    CONSTRAINT fk_erp_product_brand FOREIGN KEY (brand_id) REFERENCES erp_product_brand (id),
    CONSTRAINT fk_erp_product_default_warehouse FOREIGN KEY (default_warehouse_id) REFERENCES erp_inventory_warehouse (id),
    KEY idx_erp_product_name (tenant_id, product_name, deleted),
    KEY idx_erp_product_category (tenant_id, category_id, deleted),
    KEY idx_erp_product_brand (tenant_id, brand_id, deleted),
    KEY idx_erp_product_shelf (tenant_id, shelf_status_code, updated_time),
    KEY idx_erp_product_submit (tenant_id, submit_status_code, updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP商品主表';

CREATE TABLE erp_product_variant (
    id                      BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id               VARCHAR(64)    NOT NULL COMMENT '租户ID',
    product_id              BIGINT(20)     NOT NULL COMMENT '商品ID',
    variant_code            VARCHAR(50)    NOT NULL COMMENT '商品规格编码，由ERP编码规则生成',
    specification_snapshot  VARCHAR(500)   NULL COMMENT '规格快照，如口味/包装组合',
    unit_code               VARCHAR(64)    NULL COMMENT '订货单位，关联 PRODUCT_UNIT 字典项；草稿允许暂为空，提交时由应用服务校验',
    sale_price              DECIMAL(24,6)  NULL COMMENT '订货价；草稿允许暂为空，提交时由应用服务校验',
    market_price            DECIMAL(24,6)  NULL COMMENT '市场价',
    purchase_price          DECIMAL(24,6)  NULL COMMENT '采购参考价',
    min_order_quantity      DECIMAL(24,6)  NULL COMMENT '当前规格起订量',
    order_multiple_quantity DECIMAL(24,6)  NULL COMMENT '当前规格整倍订货数量',
    limit_quantity          DECIMAL(24,6)  NULL COMMENT '当前规格限购量',
    default_flag            TINYINT(1)     NOT NULL DEFAULT 0 COMMENT '是否默认规格：0否，1是',
    remark                  VARCHAR(1000)  NULL COMMENT '备注',
    revision                INT            NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by              VARCHAR(50)    NULL COMMENT '创建人',
    created_time            DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by              VARCHAR(50)    NULL COMMENT '更新人',
    updated_time            DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted                 INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_product_variant_code (tenant_id, variant_code),
    CONSTRAINT fk_erp_product_variant_product FOREIGN KEY (product_id) REFERENCES erp_product (id),
    KEY idx_erp_product_variant_product (tenant_id, product_id, deleted),
    KEY idx_erp_product_variant_price (tenant_id, sale_price, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP商品规格价格';

CREATE TABLE erp_procurement_order (
    id                       BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id                VARCHAR(64)    NOT NULL COMMENT '租户ID',
    procurement_no           VARCHAR(50)    NOT NULL COMMENT '采购订单号，由ERP编码规则生成',
    supplier_id              BIGINT(20)     NOT NULL COMMENT '供应商ID',
    target_warehouse_id      BIGINT(20)     NOT NULL COMMENT '计划入库仓库ID',
    status_code              VARCHAR(64)    NOT NULL DEFAULT 'DRAFT' COMMENT '采购状态，关联 PURCHASE_STATUS 字典项',
    expected_arrival_time    DATETIME(6)    NULL COMMENT '预计到货时间',
    total_quantity           DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '采购总数量，由明细汇总',
    total_amount             DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '采购总金额，由明细汇总',
    remark                   VARCHAR(1000)  NULL COMMENT '备注',
    revision                 INT            NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by               VARCHAR(50)    NULL COMMENT '创建人',
    created_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by               VARCHAR(50)    NULL COMMENT '更新人',
    updated_time             DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted                  INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_procurement_no (tenant_id, procurement_no),
    CONSTRAINT fk_erp_procurement_supplier FOREIGN KEY (supplier_id) REFERENCES erp_supplier_profile (id),
    CONSTRAINT fk_erp_procurement_warehouse FOREIGN KEY (target_warehouse_id) REFERENCES erp_inventory_warehouse (id),
    KEY idx_erp_procurement_supplier (tenant_id, supplier_id, created_time),
    KEY idx_erp_procurement_status (tenant_id, status_code, created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP采购订单';

CREATE TABLE erp_procurement_order_line (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    procurement_order_id  BIGINT(20)     NOT NULL COMMENT '采购订单ID',
    line_no               INT            NOT NULL COMMENT '行号',
    product_id            BIGINT(20)     NOT NULL COMMENT '商品ID',
    product_variant_id    BIGINT(20)     NOT NULL COMMENT '商品规格ID',
    product_code_snapshot VARCHAR(50)    NULL COMMENT '商品编码快照',
    variant_code_snapshot VARCHAR(50)    NULL COMMENT '商品规格编码快照',
    product_name_snapshot VARCHAR(200)   NOT NULL COMMENT '商品名称快照',
    unit_code             VARCHAR(64)    NOT NULL COMMENT '采购单位，关联 PRODUCT_UNIT 字典项',
    quantity              DECIMAL(24,6)  NOT NULL COMMENT '采购数量',
    unit_price            DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '采购单价',
    line_amount           DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '采购金额',
    received_quantity     DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '已入库数量',
    remark                VARCHAR(1000)  NULL COMMENT '备注',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    KEY idx_erp_procurement_line_no (tenant_id, procurement_order_id, line_no, deleted),
    CONSTRAINT fk_erp_procurement_line_order FOREIGN KEY (procurement_order_id) REFERENCES erp_procurement_order (id),
    CONSTRAINT fk_erp_procurement_line_product FOREIGN KEY (product_id) REFERENCES erp_product (id),
    CONSTRAINT fk_erp_procurement_line_variant FOREIGN KEY (product_variant_id) REFERENCES erp_product_variant (id),
    KEY idx_erp_procurement_line_product (tenant_id, product_id, product_variant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP采购订单明细';

CREATE TABLE erp_stock_balance (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    warehouse_id          BIGINT(20)     NOT NULL COMMENT '仓库ID',
    product_id            BIGINT(20)     NOT NULL COMMENT '商品ID',
    product_variant_id    BIGINT(20)     NOT NULL COMMENT '商品规格ID；无规格商品也应创建默认规格',
    available_quantity    DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '可用库存',
    locked_quantity       DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '锁定库存',
    in_transit_quantity   DECIMAL(24,6)  NOT NULL DEFAULT 0 COMMENT '在途库存',
    revision              INT            NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_stock_balance (tenant_id, warehouse_id, product_id, product_variant_id),
    CONSTRAINT fk_erp_stock_balance_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_inventory_warehouse (id),
    CONSTRAINT fk_erp_stock_balance_product FOREIGN KEY (product_id) REFERENCES erp_product (id),
    CONSTRAINT fk_erp_stock_balance_variant FOREIGN KEY (product_variant_id) REFERENCES erp_product_variant (id),
    KEY idx_erp_stock_balance_product (tenant_id, product_id, product_variant_id),
    KEY idx_erp_stock_balance_warehouse (tenant_id, warehouse_id, updated_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP库存余额表';

CREATE TABLE erp_stock_flow (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    flow_no               VARCHAR(50)    NOT NULL COMMENT '库存流水号，由ERP编码规则生成',
    warehouse_id          BIGINT(20)     NOT NULL COMMENT '仓库ID',
    product_id            BIGINT(20)     NOT NULL COMMENT '商品ID',
    product_variant_id    BIGINT(20)     NOT NULL COMMENT '商品规格ID；无规格商品也应创建默认规格',
    business_type_code    VARCHAR(64)    NOT NULL COMMENT '业务类型：PURCHASE_IN/SALES_OUT/TRANSFER_OUT/TRANSFER_IN/ADJUST',
    business_order_id     BIGINT(20)     NULL COMMENT '业务单据ID',
    business_order_no     VARCHAR(50)    NULL COMMENT '业务单据号',
    quantity_delta        DECIMAL(24,6)  NOT NULL COMMENT '库存变动数量，入库为正，出库为负',
    before_quantity       DECIMAL(24,6)  NOT NULL COMMENT '变动前可用库存',
    after_quantity        DECIMAL(24,6)  NOT NULL COMMENT '变动后可用库存',
    remark                VARCHAR(1000)  NULL COMMENT '备注',
    created_by            VARCHAR(50)    NULL COMMENT '创建人',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_stock_flow_no (tenant_id, flow_no),
    CONSTRAINT fk_erp_stock_flow_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_inventory_warehouse (id),
    CONSTRAINT fk_erp_stock_flow_product FOREIGN KEY (product_id) REFERENCES erp_product (id),
    CONSTRAINT fk_erp_stock_flow_variant FOREIGN KEY (product_variant_id) REFERENCES erp_product_variant (id),
    KEY idx_erp_stock_flow_product (tenant_id, product_id, product_variant_id, created_time),
    KEY idx_erp_stock_flow_business (tenant_id, business_type_code, business_order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP库存流水表';

CREATE TABLE erp_stock_in_order (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    stock_in_no           VARCHAR(50)    NOT NULL COMMENT '入库单号，由ERP编码规则生成',
    stock_in_type_code    VARCHAR(64)    NOT NULL COMMENT '入库类型，关联 STOCK_IN_TYPE 字典项',
    procurement_order_id  BIGINT(20)     NULL COMMENT '采购订单ID',
    procurement_no        VARCHAR(50)    NULL COMMENT '采购订单号快照',
    transfer_order_id     BIGINT(20)     NULL COMMENT '调拨单ID；调拨入库时用于追溯来源调拨单',
    transfer_order_no     VARCHAR(50)    NULL COMMENT '调拨单号快照',
    warehouse_id          BIGINT(20)     NOT NULL COMMENT '入库仓库ID',
    supplier_id           BIGINT(20)     NULL COMMENT '供应商ID',
    status_code           VARCHAR(64)    NOT NULL DEFAULT 'DRAFT' COMMENT '入库单状态，关联 STOCK_IN_STATUS 字典项',
    stock_in_time         DATETIME(6)    NULL COMMENT '确认入库时间',
    remark                VARCHAR(1000)  NULL COMMENT '备注',
    revision              INT            NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by            VARCHAR(50)    NULL COMMENT '创建人',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by            VARCHAR(50)    NULL COMMENT '更新人',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_stock_in_no (tenant_id, stock_in_no),
    CONSTRAINT fk_erp_stock_in_procurement FOREIGN KEY (procurement_order_id) REFERENCES erp_procurement_order (id),
    CONSTRAINT fk_erp_stock_in_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_inventory_warehouse (id),
    CONSTRAINT fk_erp_stock_in_supplier FOREIGN KEY (supplier_id) REFERENCES erp_supplier_profile (id),
    KEY idx_erp_stock_in_warehouse (tenant_id, warehouse_id, stock_in_time),
    KEY idx_erp_stock_in_procurement (tenant_id, procurement_order_id),
    KEY idx_erp_stock_in_transfer (tenant_id, transfer_order_no),
    KEY idx_erp_stock_in_status (tenant_id, status_code, created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP入库单';

CREATE TABLE erp_stock_in_order_line (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    stock_in_order_id     BIGINT(20)     NOT NULL COMMENT '入库单ID',
    line_no               INT            NOT NULL COMMENT '行号',
    procurement_order_line_id BIGINT(20) NULL COMMENT '采购订单明细ID；采购入库时用于回写已入库数量',
    transfer_order_line_id BIGINT(20)    NULL COMMENT '调拨单明细ID；调拨入库时用于追溯来源调拨明细',
    product_id            BIGINT(20)     NOT NULL COMMENT '商品ID',
    product_variant_id    BIGINT(20)     NOT NULL COMMENT '商品规格ID；无规格商品也应创建默认规格',
    product_code_snapshot VARCHAR(50)    NULL COMMENT '商品编码快照',
    variant_code_snapshot VARCHAR(50)    NULL COMMENT '规格编码快照',
    product_name_snapshot VARCHAR(200)   NULL COMMENT '商品名称快照',
    unit_code             VARCHAR(64)    NOT NULL COMMENT '单位，关联 PRODUCT_UNIT 字典项',
    quantity              DECIMAL(24,6)  NOT NULL COMMENT '入库数量',
    unit_price            DECIMAL(24,6)  NULL COMMENT '入库单价',
    amount                DECIMAL(24,6)  NULL COMMENT '入库金额',
    remark                VARCHAR(1000)  NULL COMMENT '备注',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    KEY idx_erp_stock_in_line_no (tenant_id, stock_in_order_id, line_no, deleted),
    CONSTRAINT fk_erp_stock_in_line_order FOREIGN KEY (stock_in_order_id) REFERENCES erp_stock_in_order (id),
    CONSTRAINT fk_erp_stock_in_line_procurement_line FOREIGN KEY (procurement_order_line_id) REFERENCES erp_procurement_order_line (id),
    CONSTRAINT fk_erp_stock_in_line_product FOREIGN KEY (product_id) REFERENCES erp_product (id),
    CONSTRAINT fk_erp_stock_in_line_variant FOREIGN KEY (product_variant_id) REFERENCES erp_product_variant (id),
    KEY idx_erp_stock_in_line_procurement (tenant_id, procurement_order_line_id),
    KEY idx_erp_stock_in_line_transfer (tenant_id, transfer_order_line_id),
    KEY idx_erp_stock_in_line_product (tenant_id, product_id, product_variant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP入库单明细';

CREATE TABLE erp_stock_out_order (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    stock_out_no          VARCHAR(50)    NOT NULL COMMENT '出库单号，由ERP编码规则生成',
    stock_out_type_code   VARCHAR(64)    NOT NULL COMMENT '出库类型，关联 STOCK_OUT_TYPE 字典项',
    warehouse_id          BIGINT(20)     NOT NULL COMMENT '出库仓库ID',
    sales_order_id        BIGINT(20)     NULL COMMENT '销售订单ID，跨Order服务引用',
    sales_order_no        VARCHAR(50)    NULL COMMENT '销售订单号快照',
    transfer_order_id     BIGINT(20)     NULL COMMENT '调拨单ID',
    transfer_order_no     VARCHAR(50)    NULL COMMENT '调拨单号快照',
    customer_id           BIGINT(20)     NULL COMMENT '客户ID，跨CRM服务引用',
    customer_name_snapshot VARCHAR(200)  NULL COMMENT '客户名称快照',
    status_code           VARCHAR(64)    NOT NULL DEFAULT 'DRAFT' COMMENT '出库单状态，关联 STOCK_OUT_STATUS 字典项',
    stock_out_time        DATETIME(6)    NULL COMMENT '确认出库时间',
    remark                VARCHAR(1000)  NULL COMMENT '备注',
    revision              INT            NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by            VARCHAR(50)    NULL COMMENT '创建人',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by            VARCHAR(50)    NULL COMMENT '更新人',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_stock_out_no (tenant_id, stock_out_no),
    CONSTRAINT fk_erp_stock_out_warehouse FOREIGN KEY (warehouse_id) REFERENCES erp_inventory_warehouse (id),
    KEY idx_erp_stock_out_sales (tenant_id, sales_order_no),
    KEY idx_erp_stock_out_transfer (tenant_id, transfer_order_no),
    KEY idx_erp_stock_out_warehouse (tenant_id, warehouse_id, stock_out_time),
    KEY idx_erp_stock_out_status (tenant_id, status_code, created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP出库单';

CREATE TABLE erp_stock_out_order_line (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    stock_out_order_id    BIGINT(20)     NOT NULL COMMENT '出库单ID',
    line_no               INT            NOT NULL COMMENT '行号',
    sales_order_line_id   BIGINT(20)     NULL COMMENT '销售订单明细ID；销售出库时用于追溯来源销售明细，跨Order服务引用不建外键',
    transfer_order_line_id BIGINT(20)    NULL COMMENT '调拨单明细ID；调拨出库时用于追溯来源调拨明细',
    product_id            BIGINT(20)     NOT NULL COMMENT '商品ID',
    product_variant_id    BIGINT(20)     NOT NULL COMMENT '商品规格ID；无规格商品也应创建默认规格',
    product_code_snapshot VARCHAR(50)    NULL COMMENT '商品编码快照',
    variant_code_snapshot VARCHAR(50)    NULL COMMENT '规格编码快照',
    product_name_snapshot VARCHAR(200)   NULL COMMENT '商品名称快照',
    unit_code             VARCHAR(64)    NOT NULL COMMENT '单位，关联 PRODUCT_UNIT 字典项',
    quantity              DECIMAL(24,6)  NOT NULL COMMENT '出库数量',
    remark                VARCHAR(1000)  NULL COMMENT '备注',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    KEY idx_erp_stock_out_line_no (tenant_id, stock_out_order_id, line_no, deleted),
    CONSTRAINT fk_erp_stock_out_line_order FOREIGN KEY (stock_out_order_id) REFERENCES erp_stock_out_order (id),
    CONSTRAINT fk_erp_stock_out_line_product FOREIGN KEY (product_id) REFERENCES erp_product (id),
    CONSTRAINT fk_erp_stock_out_line_variant FOREIGN KEY (product_variant_id) REFERENCES erp_product_variant (id),
    KEY idx_erp_stock_out_line_sales (tenant_id, sales_order_line_id),
    KEY idx_erp_stock_out_line_transfer (tenant_id, transfer_order_line_id),
    KEY idx_erp_stock_out_line_product (tenant_id, product_id, product_variant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP出库单明细';

CREATE TABLE erp_transfer_order (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    transfer_no           VARCHAR(50)    NOT NULL COMMENT '调拨单号，由ERP编码规则生成',
    source_warehouse_id   BIGINT(20)     NOT NULL COMMENT '来源仓库ID',
    target_warehouse_id   BIGINT(20)     NOT NULL COMMENT '目标仓库ID',
    status_code           VARCHAR(64)    NOT NULL DEFAULT 'DRAFT' COMMENT '调拨单状态，关联 TRANSFER_STATUS 字典项',
    stock_out_time        DATETIME(6)    NULL COMMENT '确认调拨出库时间',
    stock_in_time         DATETIME(6)    NULL COMMENT '确认调拨入库时间',
    remark                VARCHAR(1000)  NULL COMMENT '备注',
    revision              INT            NOT NULL DEFAULT 1 COMMENT '乐观锁',
    created_by            VARCHAR(50)    NULL COMMENT '创建人',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_by            VARCHAR(50)    NULL COMMENT '更新人',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_erp_transfer_no (tenant_id, transfer_no),
    CONSTRAINT fk_erp_transfer_source_warehouse FOREIGN KEY (source_warehouse_id) REFERENCES erp_inventory_warehouse (id),
    CONSTRAINT fk_erp_transfer_target_warehouse FOREIGN KEY (target_warehouse_id) REFERENCES erp_inventory_warehouse (id),
    KEY idx_erp_transfer_source (tenant_id, source_warehouse_id, created_time),
    KEY idx_erp_transfer_target (tenant_id, target_warehouse_id, created_time),
    KEY idx_erp_transfer_status (tenant_id, status_code, created_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP调拨单';

CREATE TABLE erp_transfer_order_line (
    id                    BIGINT(20)     NOT NULL AUTO_INCREMENT COMMENT 'ID',
    tenant_id             VARCHAR(64)    NOT NULL COMMENT '租户ID',
    transfer_order_id     BIGINT(20)     NOT NULL COMMENT '调拨单ID',
    line_no               INT            NOT NULL COMMENT '行号',
    product_id            BIGINT(20)     NOT NULL COMMENT '商品ID',
    product_variant_id    BIGINT(20)     NOT NULL COMMENT '商品规格ID；无规格商品也应创建默认规格',
    product_code_snapshot VARCHAR(50)    NULL COMMENT '商品编码快照',
    variant_code_snapshot VARCHAR(50)    NULL COMMENT '规格编码快照',
    product_name_snapshot VARCHAR(200)   NULL COMMENT '商品名称快照',
    unit_code             VARCHAR(64)    NOT NULL COMMENT '单位，关联 PRODUCT_UNIT 字典项',
    quantity              DECIMAL(24,6)  NOT NULL COMMENT '调拨数量',
    remark                VARCHAR(1000)  NULL COMMENT '备注',
    created_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_time          DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    deleted               INT            NOT NULL DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
    PRIMARY KEY (id),
    KEY idx_erp_transfer_line_no (tenant_id, transfer_order_id, line_no, deleted),
    CONSTRAINT fk_erp_transfer_line_order FOREIGN KEY (transfer_order_id) REFERENCES erp_transfer_order (id),
    CONSTRAINT fk_erp_transfer_line_product FOREIGN KEY (product_id) REFERENCES erp_product (id),
    CONSTRAINT fk_erp_transfer_line_variant FOREIGN KEY (product_variant_id) REFERENCES erp_product_variant (id),
    KEY idx_erp_transfer_line_product (tenant_id, product_id, product_variant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ERP调拨单明细';
