spring:
  application:
    name: "rigour-tenant-iam-service"

  # 核心：明确指定去 Nacos 拉取哪个 Data ID 和 Group（必须和 Nacos 里完全一致）
  config:
    import:
      - "nacos:rigour-iam-prod.yaml?group=DEFAULT_GROUP"

  cloud:
    nacos:
      server-addr: "127.0.0.1:8848" # 注意不要多写端口
      username: "${NACOS_USERNAME}"
      password: "${NACOS_PASSWORD}"
      discovery:
        namespace: "516560f3-8b30-4975-84cb-c55f89b912ae" # 截图里的命名空间ID
        register-enabled: true
      config:
        enabled: true # 开启配置中心
        namespace: "516560f3-8b30-4975-84cb-c55f89b912ae" # 截图里的命名空间ID
        group: "DEFAULT_GROUP"
        file-extension: "yaml"

  # 系统级开关保留在本地，避免去 Nacos 拉
  flyway:
    enabled: false

server:
  port: 26881
  servlet:
    session:
      cookie:
        secure: false # 前端是 http 时必须改 false
