package com.rigour.shared.core.api;

import org.springframework.http.HttpStatus;

/**
 * 平台通用错误码。
 * 领域错误码仍应使用 DOMAIN_REASON 命名，并明确对应的 HTTP 协议状态。
 */
public enum ErrorCode {

    BAD_REQUEST("BAD_REQUEST", "请求参数无效", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED("UNAUTHORIZED", "未认证或令牌无效", HttpStatus.UNAUTHORIZED),
    FORBIDDEN("FORBIDDEN", "无权执行当前操作", HttpStatus.FORBIDDEN),
    NOT_FOUND("NOT_FOUND", "资源不存在", HttpStatus.NOT_FOUND),
    CONFLICT("CONFLICT", "资源状态冲突", HttpStatus.CONFLICT),
    SALES_IDENTITY_UNBOUND("SALES_IDENTITY_UNBOUND", "销售身份尚未完成绑定", HttpStatus.FORBIDDEN),
    SALES_PROFILE_INACTIVE("SALES_PROFILE_INACTIVE", "销售业务身份未生效", HttpStatus.FORBIDDEN),
    SALES_POLICY_NOT_FOUND("SALES_POLICY_NOT_FOUND", "当前没有生效的销售外勤规则", HttpStatus.CONFLICT),
    SALES_WORK_DAY_NOT_FOUND("SALES_WORK_DAY_NOT_FOUND", "销售工作日不存在", HttpStatus.NOT_FOUND),
    SALES_WORK_DAY_ALREADY_ACTIVE("SALES_WORK_DAY_ALREADY_ACTIVE", "当前业务日已有进行中的销售工作日", HttpStatus.CONFLICT),
    SALES_WORK_DAY_INVALID_STATE("SALES_WORK_DAY_INVALID_STATE", "销售工作日状态不允许当前操作", HttpStatus.CONFLICT),
    SALES_IDEMPOTENCY_CONFLICT("SALES_IDEMPOTENCY_CONFLICT", "幂等键已用于不同请求", HttpStatus.CONFLICT),
    SALES_IDEMPOTENCY_IN_PROGRESS("SALES_IDEMPOTENCY_IN_PROGRESS", "相同幂等请求正在处理中", HttpStatus.CONFLICT),
    SALES_LOCATION_INVALID("SALES_LOCATION_INVALID", "定位证据无效", HttpStatus.BAD_REQUEST),
    SALES_LOCATION_BATCH_TOO_LARGE("SALES_LOCATION_BATCH_TOO_LARGE", "定位批次超过服务端限制", HttpStatus.BAD_REQUEST),
    SALES_CHECK_IN_OUTSIDE_WINDOW("SALES_CHECK_IN_OUTSIDE_WINDOW", "当前不在签到时间窗口内", HttpStatus.CONFLICT),
    SALES_CHECK_OUT_OUTSIDE_WINDOW("SALES_CHECK_OUT_OUTSIDE_WINDOW", "当前不在签退时间窗口内", HttpStatus.CONFLICT),
    SALES_VISIT_POLICY_NOT_FOUND("SALES_VISIT_POLICY_NOT_FOUND", "当前没有生效的销售拜访规则", HttpStatus.CONFLICT),
    SALES_VISIT_REQUIRES_ACTIVE_WORK_DAY("SALES_VISIT_REQUIRES_ACTIVE_WORK_DAY", "拜访需要先创建进行中的工作日", HttpStatus.CONFLICT),
    SALES_VISIT_TARGET_INVALID("SALES_VISIT_TARGET_INVALID", "拜访目标无效", HttpStatus.BAD_REQUEST),
    SALES_VISIT_OUTSIDE_RADIUS("SALES_VISIT_OUTSIDE_RADIUS", "当前位置不在拜访目标允许范围内", HttpStatus.CONFLICT),
    SALES_VISIT_NOT_FOUND("SALES_VISIT_NOT_FOUND", "拜访记录不存在", HttpStatus.NOT_FOUND),
    SALES_VISIT_INVALID_STATE("SALES_VISIT_INVALID_STATE", "拜访状态不允许当前操作", HttpStatus.CONFLICT),
    SALES_POI_INVALID("SALES_POI_INVALID", "附近门店查询参数无效", HttpStatus.BAD_REQUEST),
    SALES_POI_UPSTREAM_FAILED("SALES_POI_UPSTREAM_FAILED", "附近门店服务暂不可用", HttpStatus.SERVICE_UNAVAILABLE),
    SALES_ADMIN_INVALID("SALES_ADMIN_INVALID", "销售管理维护参数无效", HttpStatus.BAD_REQUEST),
    SALES_ADMIN_TARGET_NOT_FOUND("SALES_ADMIN_TARGET_NOT_FOUND", "销售管理维护目标不存在", HttpStatus.NOT_FOUND),
    SALES_RECORDING_INVALID("SALES_RECORDING_INVALID", "录音片段无效", HttpStatus.BAD_REQUEST),
    SALES_RECORDING_STORAGE_FAILED("SALES_RECORDING_STORAGE_FAILED", "录音存储失败", HttpStatus.INTERNAL_SERVER_ERROR),
    SALES_EVIDENCE_INVALID("SALES_EVIDENCE_INVALID", "拜访照片证据无效", HttpStatus.BAD_REQUEST),
    SALES_EVIDENCE_STORAGE_FAILED("SALES_EVIDENCE_STORAGE_FAILED", "拜访照片存储失败", HttpStatus.INTERNAL_SERVER_ERROR),
    FEISHU_JSAPI_URL_INVALID("FEISHU_JSAPI_URL_INVALID", "飞书 JSSDK 签名地址无效", HttpStatus.BAD_REQUEST),
    FEISHU_JSAPI_ORIGIN_NOT_ALLOWED("FEISHU_JSAPI_ORIGIN_NOT_ALLOWED", "飞书 JSSDK 签名来源未配置", HttpStatus.FORBIDDEN),
    FEISHU_JSAPI_CONFIG_INVALID("FEISHU_JSAPI_CONFIG_INVALID", "飞书 JSSDK 服务配置无效", HttpStatus.SERVICE_UNAVAILABLE),
    FEISHU_JSAPI_UPSTREAM_FAILED("FEISHU_JSAPI_UPSTREAM_FAILED", "飞书 JSSDK 服务暂不可用", HttpStatus.SERVICE_UNAVAILABLE),
    FEISHU_AUTH_CODE_INVALID("FEISHU_AUTH_CODE_INVALID", "飞书登录凭证无效或已过期", HttpStatus.UNAUTHORIZED),
    FEISHU_IDENTITY_NOT_BOUND("FEISHU_IDENTITY_NOT_BOUND", "飞书身份尚未绑定平台用户", HttpStatus.FORBIDDEN),
    FEISHU_AUTH_CONFIG_INVALID("FEISHU_AUTH_CONFIG_INVALID", "飞书免登服务配置无效", HttpStatus.SERVICE_UNAVAILABLE),
    FEISHU_AUTH_UPSTREAM_FAILED("FEISHU_AUTH_UPSTREAM_FAILED", "飞书免登服务暂不可用", HttpStatus.SERVICE_UNAVAILABLE),
    INTERNAL_ERROR("INTERNAL_ERROR", "服务器内部错误", HttpStatus.INTERNAL_SERVER_ERROR),
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE", "服务暂不可用", HttpStatus.SERVICE_UNAVAILABLE);

    private final String code;
    private final String message;
    private final HttpStatus httpStatus;

    ErrorCode(String code, String message, HttpStatus httpStatus) {
        this.code = code;
        this.message = message;
        this.httpStatus = httpStatus;
    }

    public String getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }

    public HttpStatus getHttpStatus() {
        return httpStatus;
    }
}
